<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto

namespace MediaCloud\Vendor\GPBMetadata\Google\Protobuf\Internal;

class Descriptor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \MediaCloud\Vendor\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->addMessage('google.protobuf.internal.FileDescriptorSet', \MediaCloud\Vendor\Google\Protobuf\Internal\FileDescriptorSet::class)
            ->repeated('file', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 1, 'google.protobuf.internal.FileDescriptorProto')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.FileDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\FileDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('package', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 2)
            ->repeated('dependency', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 3)
            ->repeated('public_dependency', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 10)
            ->repeated('weak_dependency', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 11)
            ->repeated('message_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 4, 'google.protobuf.internal.DescriptorProto')
            ->repeated('enum_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 5, 'google.protobuf.internal.EnumDescriptorProto')
            ->repeated('service', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 6, 'google.protobuf.internal.ServiceDescriptorProto')
            ->repeated('extension', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 7, 'google.protobuf.internal.FieldDescriptorProto')
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 8, 'google.protobuf.internal.FileOptions')
            ->optional('source_code_info', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 9, 'google.protobuf.internal.SourceCodeInfo')
            ->optional('syntax', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 12)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.DescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\DescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->repeated('field', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 2, 'google.protobuf.internal.FieldDescriptorProto')
            ->repeated('extension', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 6, 'google.protobuf.internal.FieldDescriptorProto')
            ->repeated('nested_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 3, 'google.protobuf.internal.DescriptorProto')
            ->repeated('enum_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 4, 'google.protobuf.internal.EnumDescriptorProto')
            ->repeated('extension_range', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 5, 'google.protobuf.internal.DescriptorProto.ExtensionRange')
            ->repeated('oneof_decl', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 8, 'google.protobuf.internal.OneofDescriptorProto')
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 7, 'google.protobuf.internal.MessageOptions')
            ->repeated('reserved_range', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 9, 'google.protobuf.internal.DescriptorProto.ReservedRange')
            ->repeated('reserved_name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 10)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.DescriptorProto.ExtensionRange', \MediaCloud\Vendor\Google\Protobuf\Internal\DescriptorProto\ExtensionRange::class)
            ->optional('start', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 1)
            ->optional('end', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 2)
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 3, 'google.protobuf.internal.ExtensionRangeOptions')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.DescriptorProto.ReservedRange', \MediaCloud\Vendor\Google\Protobuf\Internal\DescriptorProto\ReservedRange::class)
            ->optional('start', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 1)
            ->optional('end', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 2)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.ExtensionRangeOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\ExtensionRangeOptions::class)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.FieldDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\FieldDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('number', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 3)
            ->optional('label', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 4, 'google.protobuf.internal.FieldDescriptorProto.Label')
            ->optional('type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 5, 'google.protobuf.internal.FieldDescriptorProto.Type')
            ->optional('type_name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 6)
            ->optional('extendee', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 2)
            ->optional('default_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 7)
            ->optional('oneof_index', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 9)
            ->optional('json_name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 10)
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 8, 'google.protobuf.internal.FieldOptions')
            ->optional('proto3_optional', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 17)
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.FieldDescriptorProto.Type', \MediaCloud\Vendor\Google\Protobuf\Internal\Type::class)
            ->value("TYPE_DOUBLE", 1)
            ->value("TYPE_FLOAT", 2)
            ->value("TYPE_INT64", 3)
            ->value("TYPE_UINT64", 4)
            ->value("TYPE_INT32", 5)
            ->value("TYPE_FIXED64", 6)
            ->value("TYPE_FIXED32", 7)
            ->value("TYPE_BOOL", 8)
            ->value("TYPE_STRING", 9)
            ->value("TYPE_GROUP", 10)
            ->value("TYPE_MESSAGE", 11)
            ->value("TYPE_BYTES", 12)
            ->value("TYPE_UINT32", 13)
            ->value("TYPE_ENUM", 14)
            ->value("TYPE_SFIXED32", 15)
            ->value("TYPE_SFIXED64", 16)
            ->value("TYPE_SINT32", 17)
            ->value("TYPE_SINT64", 18)
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.FieldDescriptorProto.Label', \MediaCloud\Vendor\Google\Protobuf\Internal\Label::class)
            ->value("LABEL_OPTIONAL", 1)
            ->value("LABEL_REQUIRED", 2)
            ->value("LABEL_REPEATED", 3)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.OneofDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\OneofDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 2, 'google.protobuf.internal.OneofOptions')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.EnumDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\EnumDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->repeated('value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 2, 'google.protobuf.internal.EnumValueDescriptorProto')
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 3, 'google.protobuf.internal.EnumOptions')
            ->repeated('reserved_range', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 4, 'google.protobuf.internal.EnumDescriptorProto.EnumReservedRange')
            ->repeated('reserved_name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 5)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.EnumDescriptorProto.EnumReservedRange', \MediaCloud\Vendor\Google\Protobuf\Internal\EnumDescriptorProto\EnumReservedRange::class)
            ->optional('start', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 1)
            ->optional('end', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 2)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.EnumValueDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\EnumValueDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('number', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 2)
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 3, 'google.protobuf.internal.EnumValueOptions')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.ServiceDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\ServiceDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->repeated('method', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 2, 'google.protobuf.internal.MethodDescriptorProto')
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 3, 'google.protobuf.internal.ServiceOptions')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.MethodDescriptorProto', \MediaCloud\Vendor\Google\Protobuf\Internal\MethodDescriptorProto::class)
            ->optional('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('input_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 2)
            ->optional('output_type', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 3)
            ->optional('options', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 4, 'google.protobuf.internal.MethodOptions')
            ->optional('client_streaming', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 5)
            ->optional('server_streaming', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 6)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.FileOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\FileOptions::class)
            ->optional('java_package', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->optional('java_outer_classname', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 8)
            ->optional('java_multiple_files', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 10)
            ->optional('java_generate_equals_and_hash', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 20)
            ->optional('java_string_check_utf8', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 27)
            ->optional('optimize_for', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 9, 'google.protobuf.internal.FileOptions.OptimizeMode')
            ->optional('go_package', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 11)
            ->optional('cc_generic_services', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 16)
            ->optional('java_generic_services', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 17)
            ->optional('py_generic_services', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 18)
            ->optional('php_generic_services', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 42)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 23)
            ->optional('cc_enable_arenas', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 31)
            ->optional('objc_class_prefix', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 36)
            ->optional('csharp_namespace', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 37)
            ->optional('swift_prefix', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 39)
            ->optional('php_class_prefix', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 40)
            ->optional('php_namespace', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 41)
            ->optional('php_metadata_namespace', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 44)
            ->optional('ruby_package', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 45)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.FileOptions.OptimizeMode', \MediaCloud\Vendor\Google\Protobuf\Internal\OptimizeMode::class)
            ->value("SPEED", 1)
            ->value("CODE_SIZE", 2)
            ->value("LITE_RUNTIME", 3)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.MessageOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\MessageOptions::class)
            ->optional('message_set_wire_format', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 1)
            ->optional('no_standard_descriptor_accessor', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 2)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 3)
            ->optional('map_entry', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 7)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.FieldOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\FieldOptions::class)
            ->optional('ctype', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 1, 'google.protobuf.internal.FieldOptions.CType')
            ->optional('packed', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 2)
            ->optional('jstype', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 6, 'google.protobuf.internal.FieldOptions.JSType')
            ->optional('lazy', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 5)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 3)
            ->optional('weak', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 10)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.FieldOptions.CType', \MediaCloud\Vendor\Google\Protobuf\Internal\CType::class)
            ->value("STRING", 0)
            ->value("CORD", 1)
            ->value("STRING_PIECE", 2)
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.FieldOptions.JSType', \MediaCloud\Vendor\Google\Protobuf\Internal\JSType::class)
            ->value("JS_NORMAL", 0)
            ->value("JS_STRING", 1)
            ->value("JS_NUMBER", 2)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.OneofOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\OneofOptions::class)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.EnumOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\EnumOptions::class)
            ->optional('allow_alias', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 2)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 3)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.EnumValueOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\EnumValueOptions::class)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 1)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.ServiceOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\ServiceOptions::class)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 33)
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.MethodOptions', \MediaCloud\Vendor\Google\Protobuf\Internal\MethodOptions::class)
            ->optional('deprecated', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 33)
            ->optional('idempotency_level', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::ENUM, 34, 'google.protobuf.internal.MethodOptions.IdempotencyLevel')
            ->repeated('uninterpreted_option', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 999, 'google.protobuf.internal.UninterpretedOption')
            ->finalizeToPool();

        $pool->addEnum('google.protobuf.internal.MethodOptions.IdempotencyLevel', \MediaCloud\Vendor\Google\Protobuf\Internal\IdempotencyLevel::class)
            ->value("IDEMPOTENCY_UNKNOWN", 0)
            ->value("NO_SIDE_EFFECTS", 1)
            ->value("IDEMPOTENT", 2)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.UninterpretedOption', \MediaCloud\Vendor\Google\Protobuf\Internal\UninterpretedOption::class)
            ->repeated('name', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 2, 'google.protobuf.internal.UninterpretedOption.NamePart')
            ->optional('identifier_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 3)
            ->optional('positive_int_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::UINT64, 4)
            ->optional('negative_int_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT64, 5)
            ->optional('double_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::DOUBLE, 6)
            ->optional('string_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BYTES, 7)
            ->optional('aggregate_value', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 8)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.UninterpretedOption.NamePart', \MediaCloud\Vendor\Google\Protobuf\Internal\UninterpretedOption\NamePart::class)
            ->required('name_part', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 1)
            ->required('is_extension', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::BOOL, 2)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.SourceCodeInfo', \MediaCloud\Vendor\Google\Protobuf\Internal\SourceCodeInfo::class)
            ->repeated('location', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 1, 'google.protobuf.internal.SourceCodeInfo.Location')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.SourceCodeInfo.Location', \MediaCloud\Vendor\Google\Protobuf\Internal\SourceCodeInfo\Location::class)
            ->repeated('path', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 1)
            ->repeated('span', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 2)
            ->optional('leading_comments', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 3)
            ->optional('trailing_comments', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 4)
            ->repeated('leading_detached_comments', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 6)
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.GeneratedCodeInfo', \MediaCloud\Vendor\Google\Protobuf\Internal\GeneratedCodeInfo::class)
            ->repeated('annotation', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, 1, 'google.protobuf.internal.GeneratedCodeInfo.Annotation')
            ->finalizeToPool();

        $pool->addMessage('google.protobuf.internal.GeneratedCodeInfo.Annotation', \MediaCloud\Vendor\Google\Protobuf\Internal\GeneratedCodeInfo\Annotation::class)
            ->repeated('path', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 1)
            ->optional('source_file', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::STRING, 2)
            ->optional('begin', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 3)
            ->optional('end', \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::INT32, 4)
            ->finalizeToPool();

        $pool->finish();
        static::$is_initialized = true;
    }
}

