<?php

namespace MediaCloud\Vendor\Aws\FSx;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon FSx** service.
 * @method \MediaCloud\Vendor\Aws\Result associateFileSystemAliases(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateFileSystemAliasesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result cancelDataRepositoryTask(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cancelDataRepositoryTaskAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result copyBackup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise copyBackupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDataRepositoryAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDataRepositoryAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDataRepositoryTask(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDataRepositoryTaskAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFileSystemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFileSystemFromBackup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFileSystemFromBackupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createStorageVirtualMachine(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createStorageVirtualMachineAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createVolume(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createVolumeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createVolumeFromBackup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createVolumeFromBackupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBackup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBackupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDataRepositoryAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDataRepositoryAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteFileSystemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteStorageVirtualMachine(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteStorageVirtualMachineAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteVolume(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteVolumeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeBackups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeBackupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataRepositoryAssociations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDataRepositoryAssociationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataRepositoryTasks(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDataRepositoryTasksAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeFileSystemAliases(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeFileSystemAliasesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeFileSystems(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeFileSystemsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSnapshots(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeStorageVirtualMachines(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeStorageVirtualMachinesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeVolumes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeVolumesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateFileSystemAliases(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateFileSystemAliasesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result releaseFileSystemNfsV3Locks(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise releaseFileSystemNfsV3LocksAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result restoreVolumeFromSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise restoreVolumeFromSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDataRepositoryAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDataRepositoryAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateFileSystemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateStorageVirtualMachine(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateStorageVirtualMachineAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateVolume(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateVolumeAsync(array $args = [])
 */
class FSxClient extends AwsClient {}
