<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2397e21cccbd4ed63165b652a69c4b44
{
    public static $files = array (
        '0db59a7ab4e1b1877ed1ac0f4e182c8b' => __DIR__ . '/..' . '/mcloud-ralouphie/getallheaders/src/getallheaders.php',
        'd88973a1115798bc39c4d3727916968a' => __DIR__ . '/..' . '/mcloud-guzzlehttp/psr7/src/functions_include.php',
        '01de2132fd8582aacc732f7c29139a18' => __DIR__ . '/..' . '/mcloud-guzzlehttp/promises/src/functions_include.php',
        'f1afe975ad71dda85553eae5c0dd5912' => __DIR__ . '/..' . '/mcloud-paragonie/random_compat/lib/random.php',
        'f0504baa95d824eeaf99227876df27f7' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-intl-normalizer/bootstrap.php',
        'ed1721c631cd433c06716f8a8ff7f7dd' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/bootstrap.php',
        'd422443df2624afbc6952ec7fb6ae634' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php72/bootstrap.php',
        'b4b9893dfe15105f15e12291558da729' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-intl-idn/bootstrap.php',
        '6c6a6a5ff3cffa18b0cf722f4bb1b17b' => __DIR__ . '/..' . '/mcloud-guzzlehttp/guzzle/src/functions_include.php',
        'f97f2b1d7d2aabb74a40f340324ba960' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-mbstring/bootstrap.php',
        'e344b20b2f4ebbb4fd6dae4c198affe0' => __DIR__ . '/..' . '/mcloud-illuminate/support/helpers.php',
        '6cc7d496718761842feb37ed4e738a03' => __DIR__ . '/..' . '/mcloud-mtdowling/jmespath.php/src/JmesPath.php',
        '2d599bd2d501e6eeb1c2bbac9d683be6' => __DIR__ . '/..' . '/mcloud-phpseclib/phpseclib/phpseclib/bootstrap.php',
        'bcb89297df3ac264bd447901b1bd183b' => __DIR__ . '/..' . '/mcloud-sarciszewski/php-future/autoload.php',
        '99b0d9cafd1485474252d47b5d381e4e' => __DIR__ . '/..' . '/mcloud-aws/aws-sdk-php/src/functions.php',
        '947893983ac3b26acf98ee5e7f8019a8' => __DIR__ . '/..' . '/mcloud-ivopetkov/html5-dom-document-php/autoload.php',
        '6fd68b34e727d9b0914fadd5751988fb' => __DIR__ . '/..' . '/mcloud-shortpixel/shortpixel-php/lib/ShortPixel.php',
        'dc221729b1245965af5ec6f28817de1f' => __DIR__ . '/..' . '/mcloud-shortpixel/shortpixel-php/lib/ShortPixel/Exception.php',
        '2d808a684e0055c8013abc681ff83ced' => __DIR__ . '/..' . '/mcloud-tinify/tinify/lib/Tinify.php',
        '059a242f65631e838ca8515744262f41' => __DIR__ . '/..' . '/mcloud-tinify/tinify/lib/Tinify/Exception.php',
    );

    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MediaCloud\\Vendor\\phpseclib\\' => 28,
            'MediaCloud\\Vendor\\duncan3dc\\ObjectIntruder\\' => 43,
            'MediaCloud\\Vendor\\duncan3dc\\ObjectIntruderTests\\' => 48,
            'MediaCloud\\Vendor\\duncan3dc\\Laravel\\' => 36,
            'MediaCloud\\Vendor\\Zumba\\Amplitude\\Test\\' => 39,
            'MediaCloud\\Vendor\\Zumba\\Amplitude\\' => 34,
            'MediaCloud\\Vendor\\WillWashburn\\' => 31,
            'MediaCloud\\Vendor\\Tinify\\' => 25,
            'MediaCloud\\Vendor\\Symfony\\Polyfill\\Php72\\' => 41,
            'MediaCloud\\Vendor\\Symfony\\Polyfill\\Php70\\' => 41,
            'MediaCloud\\Vendor\\Symfony\\Polyfill\\Mbstring\\' => 44,
            'MediaCloud\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 51,
            'MediaCloud\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 44,
            'MediaCloud\\Vendor\\Symfony\\Component\\Translation\\' => 48,
            'MediaCloud\\Vendor\\Symfony\\Component\\Finder\\' => 43,
            'MediaCloud\\Vendor\\Symfony\\Component\\Debug\\' => 42,
            'MediaCloud\\Vendor\\ShortPixel\\' => 29,
            'MediaCloud\\Vendor\\Psr\\SimpleCache\\' => 34,
            'MediaCloud\\Vendor\\Psr\\Log\\' => 26,
            'MediaCloud\\Vendor\\Psr\\Http\\Message\\' => 35,
            'MediaCloud\\Vendor\\Psr\\Container\\' => 32,
            'MediaCloud\\Vendor\\Psr\\Cache\\' => 28,
            'MediaCloud\\Vendor\\Probe\\' => 24,
            'MediaCloud\\Vendor\\ParagonIE\\EasyRSA\\' => 36,
            'MediaCloud\\Vendor\\ParagonIE\\ConstantTime\\' => 41,
            'MediaCloud\\Vendor\\MuxPhp\\' => 25,
            'MediaCloud\\Vendor\\Monolog\\' => 26,
            'MediaCloud\\Vendor\\Mimey\\' => 24,
            'MediaCloud\\Vendor\\Lorisleiva\\CronTranslator\\' => 44,
            'MediaCloud\\Vendor\\JmesPath\\' => 27,
            'MediaCloud\\Vendor\\Illuminate\\View\\' => 34,
            'MediaCloud\\Vendor\\Illuminate\\Support\\' => 37,
            'MediaCloud\\Vendor\\Illuminate\\Filesystem\\' => 40,
            'MediaCloud\\Vendor\\Illuminate\\Events\\' => 36,
            'MediaCloud\\Vendor\\Illuminate\\Contracts\\' => 39,
            'MediaCloud\\Vendor\\Illuminate\\Container\\' => 39,
            'MediaCloud\\Vendor\\ILAB\\B2\\' => 26,
            'MediaCloud\\Vendor\\GuzzleHttp\\Psr7\\' => 34,
            'MediaCloud\\Vendor\\GuzzleHttp\\Promise\\' => 37,
            'MediaCloud\\Vendor\\GuzzleHttp\\' => 29,
            'MediaCloud\\Vendor\\Grpc\\Gcp\\' => 27,
            'MediaCloud\\Vendor\\Grpc\\' => 23,
            'MediaCloud\\Vendor\\Google\\Protobuf\\' => 34,
            'MediaCloud\\Vendor\\Google\\Cloud\\Vision\\' => 38,
            'MediaCloud\\Vendor\\Google\\Cloud\\Storage\\' => 39,
            'MediaCloud\\Vendor\\Google\\Cloud\\Core\\' => 36,
            'MediaCloud\\Vendor\\Google\\CRC32\\' => 31,
            'MediaCloud\\Vendor\\Google\\Auth\\' => 30,
            'MediaCloud\\Vendor\\Google\\ApiCore\\' => 33,
            'MediaCloud\\Vendor\\Google\\' => 25,
            'MediaCloud\\Vendor\\GPBMetadata\\Google\\Protobuf\\' => 46,
            'MediaCloud\\Vendor\\GPBMetadata\\Google\\Cloud\\Vision\\' => 50,
            'MediaCloud\\Vendor\\GPBMetadata\\Google\\' => 37,
            'MediaCloud\\Vendor\\Firebase\\JWT\\' => 31,
            'MediaCloud\\Vendor\\Doctrine\\Common\\Inflector\\' => 44,
            'MediaCloud\\Vendor\\Defuse\\Crypto\\' => 32,
            'MediaCloud\\Vendor\\Cron\\' => 23,
            'MediaCloud\\Vendor\\Aws\\' => 22,
            'MediaCloud\\Vendor\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MediaCloud\\Vendor\\phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-phpseclib/phpseclib/phpseclib',
        ),
        'MediaCloud\\Vendor\\duncan3dc\\ObjectIntruder\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-duncan3dc/object-intruder/src',
        ),
        'MediaCloud\\Vendor\\duncan3dc\\ObjectIntruderTests\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-duncan3dc/object-intruder/tests',
        ),
        'MediaCloud\\Vendor\\duncan3dc\\Laravel\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-duncan3dc/blade/src',
        ),
        'MediaCloud\\Vendor\\Zumba\\Amplitude\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-zumba/amplitude-php/test',
        ),
        'MediaCloud\\Vendor\\Zumba\\Amplitude\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-zumba/amplitude-php/src',
        ),
        'MediaCloud\\Vendor\\WillWashburn\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-willwashburn/stream/src',
        ),
        'MediaCloud\\Vendor\\Tinify\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-tinify/tinify/lib/Tinify',
        ),
        'MediaCloud\\Vendor\\Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php72',
        ),
        'MediaCloud\\Vendor\\Symfony\\Polyfill\\Php70\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70',
        ),
        'MediaCloud\\Vendor\\Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/polyfill-mbstring',
        ),
        'MediaCloud\\Vendor\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/polyfill-intl-normalizer',
        ),
        'MediaCloud\\Vendor\\Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/polyfill-intl-idn',
        ),
        'MediaCloud\\Vendor\\Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/translation',
        ),
        'MediaCloud\\Vendor\\Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/finder',
        ),
        'MediaCloud\\Vendor\\Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-symfony/debug',
        ),
        'MediaCloud\\Vendor\\ShortPixel\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-shortpixel/shortpixel-php/lib/ShortPixel',
        ),
        'MediaCloud\\Vendor\\Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-psr/simple-cache/src',
        ),
        'MediaCloud\\Vendor\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-psr/log/Psr/Log',
        ),
        'MediaCloud\\Vendor\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-psr/http-message/src',
        ),
        'MediaCloud\\Vendor\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-psr/container/src',
        ),
        'MediaCloud\\Vendor\\Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-psr/cache/src',
        ),
        'MediaCloud\\Vendor\\Probe\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-trntv/probe/src',
        ),
        'MediaCloud\\Vendor\\ParagonIE\\EasyRSA\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-paragonie/easyrsa/src',
        ),
        'MediaCloud\\Vendor\\ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-paragonie/constant_time_encoding/src',
        ),
        'MediaCloud\\Vendor\\MuxPhp\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-muxinc/mux-php/MuxPhp',
        ),
        'MediaCloud\\Vendor\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-monolog/monolog/src/Monolog',
        ),
        'MediaCloud\\Vendor\\Mimey\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-ralouphie/mimey/src',
        ),
        'MediaCloud\\Vendor\\Lorisleiva\\CronTranslator\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-lorisleiva/cron-translator/src',
        ),
        'MediaCloud\\Vendor\\JmesPath\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-mtdowling/jmespath.php/src',
        ),
        'MediaCloud\\Vendor\\Illuminate\\View\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/view',
        ),
        'MediaCloud\\Vendor\\Illuminate\\Support\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/support',
        ),
        'MediaCloud\\Vendor\\Illuminate\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/filesystem',
        ),
        'MediaCloud\\Vendor\\Illuminate\\Events\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/events',
        ),
        'MediaCloud\\Vendor\\Illuminate\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/contracts',
        ),
        'MediaCloud\\Vendor\\Illuminate\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-illuminate/container',
        ),
        'MediaCloud\\Vendor\\ILAB\\B2\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-ilab/b2-sdk-php/src',
        ),
        'MediaCloud\\Vendor\\GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-guzzlehttp/psr7/src',
        ),
        'MediaCloud\\Vendor\\GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-guzzlehttp/promises/src',
        ),
        'MediaCloud\\Vendor\\GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-guzzlehttp/guzzle/src',
        ),
        'MediaCloud\\Vendor\\Grpc\\Gcp\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src',
        ),
        'MediaCloud\\Vendor\\Grpc\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-grpc/grpc/src/lib',
        ),
        'MediaCloud\\Vendor\\Google\\Protobuf\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/protobuf/src/Google/Protobuf',
        ),
        'MediaCloud\\Vendor\\Google\\Cloud\\Vision\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/cloud-vision/src',
        ),
        'MediaCloud\\Vendor\\Google\\Cloud\\Storage\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/cloud-storage/src',
        ),
        'MediaCloud\\Vendor\\Google\\Cloud\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/cloud-core/src',
        ),
        'MediaCloud\\Vendor\\Google\\CRC32\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/crc32/src',
        ),
        'MediaCloud\\Vendor\\Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/auth/src',
        ),
        'MediaCloud\\Vendor\\Google\\ApiCore\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/gax/src',
        ),
        'MediaCloud\\Vendor\\Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/common-protos/src',
        ),
        'MediaCloud\\Vendor\\GPBMetadata\\Google\\Protobuf\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/protobuf/src/GPBMetadata/Google/Protobuf',
        ),
        'MediaCloud\\Vendor\\GPBMetadata\\Google\\Cloud\\Vision\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/cloud-vision/metadata',
        ),
        'MediaCloud\\Vendor\\GPBMetadata\\Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-google/common-protos/metadata',
            1 => __DIR__ . '/..' . '/mcloud-google/gax/metadata',
        ),
        'MediaCloud\\Vendor\\Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-firebase/php-jwt/src',
        ),
        'MediaCloud\\Vendor\\Doctrine\\Common\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'MediaCloud\\Vendor\\Defuse\\Crypto\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-defuse/php-encryption/src',
        ),
        'MediaCloud\\Vendor\\Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-dragonmantank/cron-expression/src/Cron',
        ),
        'MediaCloud\\Vendor\\Aws\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-aws/aws-sdk-php/src',
        ),
        'MediaCloud\\Vendor\\' => 
        array (
            0 => __DIR__ . '/..' . '/mcloud-nesbot/carbon/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'MediaCloud\\Vendor\\org\\bovigo\\vfs\\' => 
            array (
                0 => __DIR__ . '/..' . '/mcloud-mikey179/vfsstream/src/main/php',
            ),
            'MediaCloud\\Vendor\\Smalot\\PdfParser\\' => 
            array (
                0 => __DIR__ . '/..' . '/mcloud-smalot/pdfparser/src',
            ),
            'MediaCloud\\Vendor\\Rize\\UriTemplate' => 
            array (
                0 => __DIR__ . '/..' . '/mcloud-rize/uri-template/src',
            ),
            'MediaCloud\\Vendor\\Kraken' => 
            array (
                0 => __DIR__ . '/..' . '/mcloud-kraken-io/kraken-php/lib',
            ),
            'MediaCloud\\Vendor\\Imgix\\' => 
            array (
                0 => __DIR__ . '/..' . '/mcloud-imgix/imgix-php/src',
            ),
        ),
    );

    public static $classMap = array (
        'ArithmeticError' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/ArithmeticError.php',
        'AssertionError' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/AssertionError.php',
        'DivisionByZeroError' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/DivisionByZeroError.php',
        'Error' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/Error.php',
        'MediaCloud\\Vendor\\FasterImage\\Exception\\InvalidImageException' => __DIR__ . '/..' . '/mcloud-fasterimage/fasterimage/src/FasterImage/Exception/InvalidImageException.php',
        'MediaCloud\\Vendor\\FasterImage\\ExifParser' => __DIR__ . '/..' . '/mcloud-fasterimage/fasterimage/src/FasterImage/ExifParser.php',
        'MediaCloud\\Vendor\\FasterImage\\FasterImage' => __DIR__ . '/..' . '/mcloud-fasterimage/fasterimage/src/FasterImage/FasterImage.php',
        'MediaCloud\\Vendor\\FasterImage\\ImageParser' => __DIR__ . '/..' . '/mcloud-fasterimage/fasterimage/src/FasterImage/ImageParser.php',
        'MediaCloud\\Vendor\\GPBMetadata\\GrpcGcp' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/GPBMetadata/GrpcGcp.php',
        'MediaCloud\\Vendor\\Grpc\\Gcp\\AffinityConfig' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/Grpc/Gcp/AffinityConfig.php',
        'MediaCloud\\Vendor\\Grpc\\Gcp\\AffinityConfig_Command' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/Grpc/Gcp/AffinityConfig_Command.php',
        'MediaCloud\\Vendor\\Grpc\\Gcp\\ApiConfig' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/Grpc/Gcp/ApiConfig.php',
        'MediaCloud\\Vendor\\Grpc\\Gcp\\ChannelPoolConfig' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/Grpc/Gcp/ChannelPoolConfig.php',
        'MediaCloud\\Vendor\\Grpc\\Gcp\\MethodConfig' => __DIR__ . '/..' . '/mcloud-google/grpc-gcp/src/generated/Grpc/Gcp/MethodConfig.php',
        'MediaCloud\\Vendor\\Imagify\\Optimizer' => __DIR__ . '/..' . '/mcloud-wp-media/imagify-php/class-imagify.php',
        'Normalizer' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
        'ParseError' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/ParseError.php',
        'SessionUpdateTimestampHandlerInterface' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/SessionUpdateTimestampHandlerInterface.php',
        'TypeError' => __DIR__ . '/..' . '/mcloud-symfony/polyfill-php70/Resources/stubs/TypeError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2397e21cccbd4ed63165b652a69c4b44::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2397e21cccbd4ed63165b652a69c4b44::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit2397e21cccbd4ed63165b652a69c4b44::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit2397e21cccbd4ed63165b652a69c4b44::$classMap;

        }, null, ClassLoader::class);
    }
}
