<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '97e0c010726f0e1b514c56801385dc8d26d53bf8',
        'name' => 'ilab/ilab-media-tools',
        'dev' => true,
    ),
    'versions' => array(
        'ilab/ilab-media-tools' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '97e0c010726f0e1b514c56801385dc8d26d53bf8',
            'dev_requirement' => false,
        ),
        'mcloud-aws/aws-crt-php' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-aws/aws-crt-php',
            'aliases' => array(),
            'reference' => 'b36ce7fbc3a8b744e2fd429be2ff80d4d39e2a0e',
            'dev_requirement' => false,
        ),
        'mcloud-aws/aws-sdk-php' => array(
            'pretty_version' => '3.211.1',
            'version' => '3.211.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-aws/aws-sdk-php',
            'aliases' => array(),
            'reference' => '70334180b72c224f3aad869506733ee805913107',
            'dev_requirement' => false,
        ),
        'mcloud-defuse/php-encryption' => array(
            'pretty_version' => 'v2.3.1',
            'version' => '2.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-defuse/php-encryption',
            'aliases' => array(),
            'reference' => 'c99cd88a6a3f314fd82e5dc2c2147bb6a50a99f3',
            'dev_requirement' => false,
        ),
        'mcloud-doctrine/inflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-doctrine/inflector',
            'aliases' => array(),
            'reference' => '1523d10c6407a4862be37f5dd3138bc8b30f5786',
            'dev_requirement' => false,
        ),
        'mcloud-dragonmantank/cron-expression' => array(
            'pretty_version' => 'v3.3.1',
            'version' => '3.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-dragonmantank/cron-expression',
            'aliases' => array(),
            'reference' => '860f2d574d0e36b7f62fa4ef933d6bd05f4cd3b4',
            'dev_requirement' => false,
        ),
        'mcloud-duncan3dc/blade' => array(
            'pretty_version' => '4.11.0',
            'version' => '4.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-duncan3dc/blade',
            'aliases' => array(),
            'reference' => '58ea5b4623a6b11d7bf5dbcdbc0923a27138c979',
            'dev_requirement' => false,
        ),
        'mcloud-duncan3dc/object-intruder' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-duncan3dc/object-intruder',
            'aliases' => array(),
            'reference' => '1904ea7aaa181cbfb17ef9c2edbdd1478eb9c212',
            'dev_requirement' => false,
        ),
        'mcloud-fasterimage/fasterimage' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-fasterimage/fasterimage',
            'aliases' => array(),
            'reference' => 'ba12eebe5a80694f86de690c70d0111cee1994bd',
            'dev_requirement' => false,
        ),
        'mcloud-firebase/php-jwt' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'f6f794c5df85ac58417391d91ae4e5f0d6b91b15',
            'dev_requirement' => false,
        ),
        'mcloud-google/auth' => array(
            'pretty_version' => 'v1.18.0',
            'version' => '1.18.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/auth',
            'aliases' => array(),
            'reference' => '00e46193d583f55fc67fa144026a3d00a0206424',
            'dev_requirement' => false,
        ),
        'mcloud-google/cloud-core' => array(
            'pretty_version' => 'v1.44.0',
            'version' => '1.44.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/cloud-core',
            'aliases' => array(),
            'reference' => '064254aefff3fe634280cbab5dba8dce293a93cb',
            'dev_requirement' => false,
        ),
        'mcloud-google/cloud-storage' => array(
            'pretty_version' => 'v1.26.1',
            'version' => '1.26.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/cloud-storage',
            'aliases' => array(),
            'reference' => '3eed1ec6e38c2d8abf3d97fc2087afd0b37e589a',
            'dev_requirement' => false,
        ),
        'mcloud-google/cloud-vision' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/cloud-vision',
            'aliases' => array(),
            'reference' => 'a448d8649d1964a06f820a262ac7622cf08623f2',
            'dev_requirement' => false,
        ),
        'mcloud-google/common-protos' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/common-protos',
            'aliases' => array(),
            'reference' => '0f5c25861f28e144d0b643b9889b858fa3baceb7',
            'dev_requirement' => false,
        ),
        'mcloud-google/crc32' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/crc32',
            'aliases' => array(),
            'reference' => '76d43c0ef14dece170164f11fb8d01c73c7f6f02',
            'dev_requirement' => false,
        ),
        'mcloud-google/gax' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/gax',
            'aliases' => array(),
            'reference' => '0cf2256b634f89771bc64d822a0d20c9437de5a9',
            'dev_requirement' => false,
        ),
        'mcloud-google/grpc-gcp' => array(
            'pretty_version' => 'v0.2.0',
            'version' => '0.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/grpc-gcp',
            'aliases' => array(),
            'reference' => '02d9ae1d14b39b314b12b0c14eeac97a66c4a30b',
            'dev_requirement' => false,
        ),
        'mcloud-google/protobuf' => array(
            'pretty_version' => 'v3.19.4',
            'version' => '3.19.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-google/protobuf',
            'aliases' => array(),
            'reference' => '7a7fda18144ec20a832c99bfaca4a06862258aef',
            'dev_requirement' => false,
        ),
        'mcloud-grpc/grpc' => array(
            'pretty_version' => '1.42.0',
            'version' => '1.42.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-grpc/grpc',
            'aliases' => array(),
            'reference' => '366a31680e90d11c214161ecd14a1512893c4214',
            'dev_requirement' => false,
        ),
        'mcloud-guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '21365cdd9b9e375ae671dd4e5664e9863b02b9b2',
            'dev_requirement' => false,
        ),
        'mcloud-guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'a4f3a4771006474cb39849d275cd215e7a866537',
            'dev_requirement' => false,
        ),
        'mcloud-guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'e848c6d21737116d1fda35f885938b9cfe0fb015',
            'dev_requirement' => false,
        ),
        'mcloud-ilab/b2-sdk-php' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-ilab/b2-sdk-php',
            'aliases' => array(),
            'reference' => 'f64a1f45c1b4d058a71f7e3c00718e5c806efef0',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/container' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/container',
            'aliases' => array(),
            'reference' => '4f381edafc5473412d54c0d0478360d108077d80',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/contracts' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/contracts',
            'aliases' => array(),
            'reference' => '4f0b549fdd8c38e9c590ea03d63c2e05fa669885',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/events' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/events',
            'aliases' => array(),
            'reference' => '3153999960d4a979288abbbd024a8c8223793563',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/filesystem' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/filesystem',
            'aliases' => array(),
            'reference' => 'd93b59b5f85299d38a293f9c30e65594da99a249',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/support' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/support',
            'aliases' => array(),
            'reference' => 'fb068d844bfbea03128a1827e8e163ea742acefe',
            'dev_requirement' => false,
        ),
        'mcloud-illuminate/view' => array(
            'pretty_version' => 'v7.30.6',
            'version' => '7.30.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-illuminate/view',
            'aliases' => array(),
            'reference' => '9b1a709a97b79fcbef0cbaa85566c2eba7d48126',
            'dev_requirement' => false,
        ),
        'mcloud-imgix/imgix-php' => array(
            'pretty_version' => '3.3.1',
            'version' => '3.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-imgix/imgix-php',
            'aliases' => array(),
            'reference' => '264c829f55296536479e9ebb5d8221eacb2ff60e',
            'dev_requirement' => false,
        ),
        'mcloud-ivopetkov/html5-dom-document-php' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-ivopetkov/html5-dom-document-php',
            'aliases' => array(),
            'reference' => 'db3005e4a4aea2da8434b6369dd21fecf6f48b51',
            'dev_requirement' => false,
        ),
        'mcloud-kraken-io/kraken-php' => array(
            'pretty_version' => '1.6',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-kraken-io/kraken-php',
            'aliases' => array(),
            'reference' => 'fd0de78ea65a163b76d730c05c50bbe45af4c801',
            'dev_requirement' => false,
        ),
        'mcloud-lorisleiva/cron-translator' => array(
            'pretty_version' => 'v0.3.1',
            'version' => '0.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-lorisleiva/cron-translator',
            'aliases' => array(),
            'reference' => 'ce3fd295146bdc6c459974e4eae697ebb17a52a2',
            'dev_requirement' => false,
        ),
        'mcloud-mikey179/vfsstream' => array(
            'pretty_version' => 'v1.6.10',
            'version' => '1.6.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-mikey179/vfsstream',
            'aliases' => array(),
            'reference' => '695c5ae854341461932c61ccf39d452ee45f2eae',
            'dev_requirement' => false,
        ),
        'mcloud-monolog/monolog' => array(
            'pretty_version' => '2.3.5',
            'version' => '2.3.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-monolog/monolog',
            'aliases' => array(),
            'reference' => '1c9be2f427bb698e3d9f11704792fc857f658417',
            'dev_requirement' => false,
        ),
        'mcloud-mtdowling/jmespath.php' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-mtdowling/jmespath.php',
            'aliases' => array(),
            'reference' => '1f25441d3f8a6e02e6e7c05b3da113e36aad23aa',
            'dev_requirement' => false,
        ),
        'mcloud-muxinc/mux-php' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-muxinc/mux-php',
            'aliases' => array(),
            'reference' => 'ec30ee90bb39f83659484a091d5b67b41e5ec0b5',
            'dev_requirement' => false,
        ),
        'mcloud-nesbot/carbon' => array(
            'pretty_version' => '2.57.0',
            'version' => '2.57.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-nesbot/carbon',
            'aliases' => array(),
            'reference' => '78fdd2d2d91dcf10acd8a7deb8578b6cb40e8647',
            'dev_requirement' => false,
        ),
        'mcloud-paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-paragonie/constant_time_encoding',
            'aliases' => array(),
            'reference' => 'fd6a45ea3c6da02b45dc6710ea88133abacfe1b9',
            'dev_requirement' => false,
        ),
        'mcloud-paragonie/easyrsa' => array(
            'pretty_version' => 'v0.6.0',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-paragonie/easyrsa',
            'aliases' => array(),
            'reference' => 'b80b8eb95df769f04912c67f056791e3ad32a3ba',
            'dev_requirement' => false,
        ),
        'mcloud-paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-paragonie/random_compat',
            'aliases' => array(),
            'reference' => '13537b4757b04f297289a1b8818ac8017e2bc852',
            'dev_requirement' => false,
        ),
        'mcloud-phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.36',
            'version' => '2.0.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => 'cc7d137148a856e755fe1310c657d04504397861',
            'dev_requirement' => false,
        ),
        'mcloud-psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/cache',
            'aliases' => array(),
            'reference' => '0a662416af77f2b343a4b3cb6ccf983cf8fa1ae9',
            'dev_requirement' => false,
        ),
        'mcloud-psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/container',
            'aliases' => array(),
            'reference' => 'ce57afe6371fa5f8e9d3c3a5b8fe19c743e42353',
            'dev_requirement' => false,
        ),
        'mcloud-psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/event-dispatcher',
            'aliases' => array(),
            'reference' => '35bb302a6cd33e0c3665473ef71c24fde5a02f7f',
            'dev_requirement' => false,
        ),
        'mcloud-psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/http-message',
            'aliases' => array(),
            'reference' => 'c049bc02563562a5051cf9466915ef1c6bd22bef',
            'dev_requirement' => false,
        ),
        'mcloud-psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/log',
            'aliases' => array(),
            'reference' => '1050f89dedbd3dc61ce4cd0558397693fbb8b7ac',
            'dev_requirement' => false,
        ),
        'mcloud-psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-psr/simple-cache',
            'aliases' => array(),
            'reference' => 'f4994e0a44d2202ab6639a2c067e05615274a216',
            'dev_requirement' => false,
        ),
        'mcloud-ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => 'd7771366bb8270f21915cfd970855c3287223b86',
            'dev_requirement' => false,
        ),
        'mcloud-ralouphie/mimey' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-ralouphie/mimey',
            'aliases' => array(),
            'reference' => 'ff8ae27bcb93c7e3d2842d4044f09a6f6b3fa2d7',
            'dev_requirement' => false,
        ),
        'mcloud-rize/uri-template' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-rize/uri-template',
            'aliases' => array(),
            'reference' => 'acc3e14a972c80afaba58b5b25ae08f2c0b08436',
            'dev_requirement' => false,
        ),
        'mcloud-shortpixel/shortpixel-php' => array(
            'pretty_version' => 'v1.8.7',
            'version' => '1.8.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-shortpixel/shortpixel-php',
            'aliases' => array(),
            'reference' => 'b08329cf84b08daafa015b116168f94a9249ada0',
            'dev_requirement' => false,
        ),
        'mcloud-smalot/pdfparser' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-smalot/pdfparser',
            'aliases' => array(),
            'reference' => '3594d1e4fe0e379c697b6fc8bc5cdf066726f3c7',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/amqp-messenger' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'symfony-messenger-bridge',
            'install_path' => __DIR__ . '/../mcloud-symfony/amqp-messenger',
            'aliases' => array(),
            'reference' => 'f1b3920ad088f1f63aaec4015eaf1458a79f6b7d',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/browser-kit' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/browser-kit',
            'aliases' => array(),
            'reference' => '07cbc45b4c900c91fb0285c421f45c55133cbefd',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/cache' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/cache',
            'aliases' => array(),
            'reference' => 'd3178a46e0a2f2b000ef4352cb42e5b7591df12a',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/cache-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/cache-contracts',
            'aliases' => array(),
            'reference' => 'ab16d8ae53cf54360ab6f14c6f44d0ca4d810fd8',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/config' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/config',
            'aliases' => array(),
            'reference' => 'c190b98eb4ec4623809664a72569f167e4acc0d0',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/console' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/console',
            'aliases' => array(),
            'reference' => 'ca3a676f73c5b79c481555e2abbd4484bb435861',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/debug' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/debug',
            'aliases' => array(),
            'reference' => '72505ad8b9644fa8e3f4cc5ce305de5605a47621',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/dependency-injection' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/dependency-injection',
            'aliases' => array(),
            'reference' => '942c9e8e503cbed8f219f44aae4edb7a2faf40ab',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => '37b96f078fac5cd404902d713a7b84bd64be6e8e',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/doctrine-messenger' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'symfony-messenger-bridge',
            'install_path' => __DIR__ . '/../mcloud-symfony/doctrine-messenger',
            'aliases' => array(),
            'reference' => '64f3af8c23112cbc3a1f2e212ad78a5fbef152a8',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/dom-crawler' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/dom-crawler',
            'aliases' => array(),
            'reference' => '96953c9f43361f50b7ff93fc382cb2b64da48e7f',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/error-handler' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/error-handler',
            'aliases' => array(),
            'reference' => 'ccad7819cebb3f9984b08610ba09810c5f70bb70',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => 'eee8ba27b8c1db6cd740de31b91ec6c6edca051b',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'reference' => 'f590cfec2b33e25c01ab9004787d8ed68e839938',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/expression-language' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/expression-language',
            'aliases' => array(),
            'reference' => '35fb89ad302bde00afbb007d450f8b3b8ae90597',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/filesystem' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/filesystem',
            'aliases' => array(),
            'reference' => '4006b175d64706e9938dc7e6c06bd1898350d6c7',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/finder' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/finder',
            'aliases' => array(),
            'reference' => '846a5e17365ccefec095b55f46f9501ff668509e',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/http-client' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/http-client',
            'aliases' => array(),
            'reference' => 'd7433ed6ced8419ff0d71830a69ad61bc2901c85',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => 'b1d981b2c8e95980ef4c4340bd931a3621de748b',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/http-foundation' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/http-foundation',
            'aliases' => array(),
            'reference' => 'b1f3443d2498f7f4b21df8e06ddbe79c7083a32a',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/http-kernel' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/http-kernel',
            'aliases' => array(),
            'reference' => '66b11d81792127287278f5e9ad2c6feac48504f2',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/lock' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/lock',
            'aliases' => array(),
            'reference' => 'ad98298304c83113966043187e2455faca05231b',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/messenger' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/messenger',
            'aliases' => array(),
            'reference' => '67a6e40fdf9816576182732fc367c339a660e3fa',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/mime' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/mime',
            'aliases' => array(),
            'reference' => '745dc872e498514680e721aec3652bb8d0b820d3',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/options-resolver' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/options-resolver',
            'aliases' => array(),
            'reference' => '873091eaa151a6521930f17c322baf32cb691861',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => 'da2dae0925b46b2b57b474080fec5ee598fcf486',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'reference' => '7d6c9672b95fcae373c4d91fc689d35b32fc0d6d',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '36657c55933fa020744c3209c3bdd9fe242e8108',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '1f48ad88fdde26895d2434d14884deefb6051862',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'a716a34c47fd46e094c71aec00b4f83269480963',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => 'ca13bb31fc804175abda5a297d8085754dc2a044',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'c398a137561ebef2a31162ffff2ad559d82841bd',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => 'e1729ed98348d20d6840377be822bc529ad3b619',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => '7d76eca7771a9f4c7fc42ce2516cdad4b530e863',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/polyfill-uuid' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/polyfill-uuid',
            'aliases' => array(),
            'reference' => 'cf9f623011681a7b13d9e497555ca6187c205282',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/process' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/process',
            'aliases' => array(),
            'reference' => '5deebdb3443f5532596e329170a78398b60dd259',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/property-info' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/property-info',
            'aliases' => array(),
            'reference' => 'b1c4da410c73411d10e009da001dcb4c7a9f84b2',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/rate-limiter' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/rate-limiter',
            'aliases' => array(),
            'reference' => '272210000f526102e12ee82de604ece2fb1148a2',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/redis-messenger' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'symfony-messenger-bridge',
            'install_path' => __DIR__ . '/../mcloud-symfony/redis-messenger',
            'aliases' => array(),
            'reference' => 'dcf93de5538dfde7ad10cfdb9541953b36c127d3',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/routing' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/routing',
            'aliases' => array(),
            'reference' => '9612bd7c8ab34e5509e06489b88601480829f4f7',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/serializer' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/serializer',
            'aliases' => array(),
            'reference' => '3cd8c26eeaccec78cb047b851e4e73761b00ed6a',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/service-contracts',
            'aliases' => array(),
            'reference' => '5d902a8e4a62e6582e383fe94107cc3b5bc2de35',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/stopwatch' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/stopwatch',
            'aliases' => array(),
            'reference' => 'b5558d46fdb3712e3070a0060acd23d62f573268',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/string' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/string',
            'aliases' => array(),
            'reference' => 'd039c41e6d3b2265ea7518cd765a0350fcbeace9',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/translation' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/translation',
            'aliases' => array(),
            'reference' => 'ff4c5c5b26fb72ddc2c6a26197dcf2a7bfe71900',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '4bdf1d63c7138ce20adbed16fb7627e09ac0eb7c',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/uid' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/uid',
            'aliases' => array(),
            'reference' => '05a10d9bb560d205d063420a055f21aa90a46fc2',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/validator' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/validator',
            'aliases' => array(),
            'reference' => 'c9cd4824f8fb52cf6c402ee37412795724be14d3',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/var-dumper' => array(
            'pretty_version' => 'v5.4.5',
            'version' => '5.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/var-dumper',
            'aliases' => array(),
            'reference' => 'c9d19fe56071599040799e7e9fa5d9bbb622c5c2',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/var-exporter' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/var-exporter',
            'aliases' => array(),
            'reference' => '37ba5e1bf256728fb43dffcbdd0e3487791e7ac6',
            'dev_requirement' => false,
        ),
        'mcloud-symfony/yaml' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-symfony/yaml',
            'aliases' => array(),
            'reference' => '2d65fad43ddd828d21b9a416839c79cd74be7f9f',
            'dev_requirement' => false,
        ),
        'mcloud-tinify/tinify' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-tinify/tinify',
            'aliases' => array(),
            'reference' => 'a520600fac00c9aed391b95603286edc4e1c9091',
            'dev_requirement' => false,
        ),
        'mcloud-trntv/probe' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-trntv/probe',
            'aliases' => array(),
            'reference' => 'fced3d2b7ccbc18cd2b975488700ba062b4767e9',
            'dev_requirement' => false,
        ),
        'mcloud-voku/portable-ascii' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-voku/portable-ascii',
            'aliases' => array(),
            'reference' => '629bde2fc81978862dd32db81601062b6d9e576a',
            'dev_requirement' => false,
        ),
        'mcloud-webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-webmozart/assert',
            'aliases' => array(),
            'reference' => '1fe99a78b76426a6caeb7c31d7452f1dd80d76eb',
            'dev_requirement' => false,
        ),
        'mcloud-willwashburn/stream' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-willwashburn/stream',
            'aliases' => array(),
            'reference' => '5f022dfd302579a0c3267be49a81d4960dedb4f3',
            'dev_requirement' => false,
        ),
        'mcloud-wp-media/imagify-php' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-wp-media/imagify-php',
            'aliases' => array(),
            'reference' => '94ac9a01740a42b2b0dbe0e13ad12092de0a8680',
            'dev_requirement' => false,
        ),
        'mcloud-zumba/amplitude-php' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mcloud-zumba/amplitude-php',
            'aliases' => array(),
            'reference' => 'd0c7f4a99e41bfa2318d67e169940844a8324a91',
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.0',
            ),
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
                1 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.4',
            ),
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.3',
            ),
        ),
    ),
);
