<?php

namespace MediaCloud\Vendor\Aws\CloudSearch;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon CloudSearch** service.
 *
 * @method \MediaCloud\Vendor\Aws\Result buildSuggesters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise buildSuggestersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result defineAnalysisScheme(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise defineAnalysisSchemeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result defineExpression(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise defineExpressionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result defineIndexField(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise defineIndexFieldAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result defineSuggester(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise defineSuggesterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAnalysisScheme(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAnalysisSchemeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteExpression(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteExpressionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteIndexField(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteIndexFieldAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSuggester(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSuggesterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAnalysisSchemes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAnalysisSchemesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAvailabilityOptions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAvailabilityOptionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDomainEndpointOptions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDomainEndpointOptionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDomains(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDomainsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeExpressions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeExpressionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeIndexFields(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeIndexFieldsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeScalingParameters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeScalingParametersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeServiceAccessPolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeServiceAccessPoliciesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSuggesters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSuggestersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result indexDocuments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise indexDocumentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDomainNames(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDomainNamesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateAvailabilityOptions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAvailabilityOptionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDomainEndpointOptions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDomainEndpointOptionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateScalingParameters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateScalingParametersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateServiceAccessPolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateServiceAccessPoliciesAsync(array $args = [])
 */
class CloudSearchClient extends AwsClient {}
