<?php

namespace MediaCloud\Vendor\Aws\Schemas;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Schemas** service.
 * @method \MediaCloud\Vendor\Aws\Result createDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRegistry(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRegistryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSchemaAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRegistry(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRegistryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSchemaAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSchemaVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSchemaVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeCodeBinding(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeCodeBindingAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeRegistry(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeRegistryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSchemaAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCodeBindingSource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCodeBindingSourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getDiscoveredSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getDiscoveredSchemaAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDiscoverers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDiscoverersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRegistries(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRegistriesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSchemaVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSchemaVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSchemas(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSchemasAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putCodeBinding(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putCodeBindingAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result searchSchemas(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise searchSchemasAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDiscoverer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDiscovererAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRegistry(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRegistryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSchemaAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result exportSchema(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise exportSchemaAsync(array $args = [])
 */
class SchemasClient extends AwsClient {}
