<?php

namespace MediaCloud\Vendor\Aws\Kinesis;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Kinesis** service.
 *
 * @method \MediaCloud\Vendor\Aws\Result addTagsToStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise addTagsToStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result decreaseStreamRetentionPeriod(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise decreaseStreamRetentionPeriodAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deregisterStreamConsumer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deregisterStreamConsumerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeLimits(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeLimitsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeStreamConsumer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeStreamConsumerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeStreamSummary(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeStreamSummaryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disableEnhancedMonitoring(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disableEnhancedMonitoringAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result enableEnhancedMonitoring(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise enableEnhancedMonitoringAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRecords(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRecordsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getShardIterator(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getShardIteratorAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result increaseStreamRetentionPeriod(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise increaseStreamRetentionPeriodAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listShards(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listShardsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listStreamConsumers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listStreamConsumersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listStreams(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listStreamsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result mergeShards(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise mergeShardsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putRecord(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putRecordAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putRecords(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putRecordsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result registerStreamConsumer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise registerStreamConsumerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeTagsFromStream(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeTagsFromStreamAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result splitShard(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise splitShardAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startStreamEncryption(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startStreamEncryptionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopStreamEncryption(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopStreamEncryptionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateShardCount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateShardCountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateStreamMode(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateStreamModeAsync(array $args = [])
 */
class KinesisClient extends AwsClient {}
