<?php

namespace MediaCloud\Vendor\Aws\MediaStore;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Elemental MediaStore** service.
 * @method \MediaCloud\Vendor\Aws\Result createContainer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createContainerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteContainer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteContainerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteContainerPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteContainerPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCorsPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteCorsPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteLifecyclePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteLifecyclePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteMetricPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteMetricPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeContainer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeContainerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getContainerPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getContainerPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCorsPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCorsPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getLifecyclePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getLifecyclePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMetricPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMetricPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listContainers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listContainersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putContainerPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putContainerPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putCorsPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putCorsPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putLifecyclePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putLifecyclePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putMetricPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putMetricPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startAccessLogging(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startAccessLoggingAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopAccessLogging(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopAccessLoggingAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 */
class MediaStoreClient extends AwsClient {}
