<?php

namespace MediaCloud\Vendor\Aws\Route53RecoveryReadiness;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Route53 Recovery Readiness** service.
 * @method \MediaCloud\Vendor\Aws\Result createCell(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createCellAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createCrossAccountAuthorization(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createCrossAccountAuthorizationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createReadinessCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createReadinessCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRecoveryGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRecoveryGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createResourceSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createResourceSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCell(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteCellAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCrossAccountAuthorization(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteCrossAccountAuthorizationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteReadinessCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteReadinessCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRecoveryGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRecoveryGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteResourceSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteResourceSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getArchitectureRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getArchitectureRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCell(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCellAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCellReadinessSummary(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCellReadinessSummaryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getReadinessCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getReadinessCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getReadinessCheckResourceStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getReadinessCheckResourceStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getReadinessCheckStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getReadinessCheckStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRecoveryGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRecoveryGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRecoveryGroupReadinessSummary(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRecoveryGroupReadinessSummaryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourceSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourceSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCells(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCellsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCrossAccountAuthorizations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCrossAccountAuthorizationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listReadinessChecks(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listReadinessChecksAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRecoveryGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRecoveryGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listResourceSets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listResourceSetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRules(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRulesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateCell(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateCellAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateReadinessCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateReadinessCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRecoveryGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRecoveryGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateResourceSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateResourceSetAsync(array $args = [])
 */
class Route53RecoveryReadinessClient extends AwsClient {}
