<?php

namespace MediaCloud\Vendor\Aws\LookoutEquipment;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Lookout for Equipment** service.
 * @method \MediaCloud\Vendor\Aws\Result createDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createInferenceSchedulerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createModel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createModelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteInferenceSchedulerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteModel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteModelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataIngestionJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDataIngestionJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeInferenceSchedulerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeModel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeModelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDataIngestionJobs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDataIngestionJobsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDatasets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDatasetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listInferenceExecutions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listInferenceExecutionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listInferenceSchedulers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listInferenceSchedulersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listModels(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listModelsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startDataIngestionJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startDataIngestionJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startInferenceSchedulerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopInferenceSchedulerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateInferenceScheduler(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateInferenceSchedulerAsync(array $args = [])
 */
class LookoutEquipmentClient extends AwsClient {}
