<?php

namespace MediaCloud\Vendor\Aws\GreengrassV2;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS IoT Greengrass V2** service.
 * @method \MediaCloud\Vendor\Aws\Result associateServiceRoleToAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateServiceRoleToAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchAssociateClientDeviceWithCoreDevice(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchAssociateClientDeviceWithCoreDeviceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchDisassociateClientDeviceFromCoreDevice(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchDisassociateClientDeviceFromCoreDeviceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result cancelDeployment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cancelDeploymentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createComponentVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createComponentVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDeployment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDeploymentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteComponent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteComponentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCoreDevice(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteCoreDeviceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeComponent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeComponentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateServiceRoleFromAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateServiceRoleFromAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getComponent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getComponentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getComponentVersionArtifact(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getComponentVersionArtifactAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getConnectivityInfo(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getConnectivityInfoAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCoreDevice(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCoreDeviceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getDeployment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getDeploymentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getServiceRoleForAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getServiceRoleForAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listClientDevicesAssociatedWithCoreDevice(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listClientDevicesAssociatedWithCoreDeviceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listComponentVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listComponentVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listComponents(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listComponentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCoreDevices(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCoreDevicesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDeployments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDeploymentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listEffectiveDeployments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listEffectiveDeploymentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listInstalledComponents(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listInstalledComponentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result resolveComponentCandidates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise resolveComponentCandidatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateConnectivityInfo(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateConnectivityInfoAsync(array $args = [])
 */
class GreengrassV2Client extends AwsClient {}
