<?php

namespace MediaCloud\Vendor\Aws\WellArchitected;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Well-Architected Tool** service.
 * @method \MediaCloud\Vendor\Aws\Result associateLenses(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateLensesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createLensShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createLensShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createLensVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createLensVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createMilestone(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createMilestoneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createWorkload(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createWorkloadAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createWorkloadShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createWorkloadShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteLens(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteLensAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteLensShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteLensShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteWorkload(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteWorkloadAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteWorkloadShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteWorkloadShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateLenses(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateLensesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result exportLens(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise exportLensAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAnswer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAnswerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getLens(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getLensAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getLensReview(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getLensReviewAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getLensReviewReport(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getLensReviewReportAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getLensVersionDifference(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getLensVersionDifferenceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMilestone(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMilestoneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getWorkload(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getWorkloadAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result importLens(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise importLensAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAnswers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAnswersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listLensReviewImprovements(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listLensReviewImprovementsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listLensReviews(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listLensReviewsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listLensShares(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listLensSharesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listLenses(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listLensesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listMilestones(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listMilestonesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listNotifications(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listNotificationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listShareInvitations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listShareInvitationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listWorkloadShares(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listWorkloadSharesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listWorkloads(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listWorkloadsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateAnswer(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAnswerAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateLensReview(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateLensReviewAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateShareInvitation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateShareInvitationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateWorkload(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateWorkloadAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateWorkloadShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateWorkloadShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result upgradeLensReview(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise upgradeLensReviewAsync(array $args = [])
 */
class WellArchitectedClient extends AwsClient {}
