<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto

namespace MediaCloud\Vendor\Google\Protobuf\Internal;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Protobuf\Internal\FieldOptions\JSType instead.
     * @deprecated
     */
    class FieldOptions_JSType {}
}
class_exists(FieldOptions\JSType::class);
@trigger_error('MediaCloud\Vendor\Google\Protobuf\Internal\FieldOptions_JSType is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Protobuf\Internal\FieldOptions\JSType instead', E_USER_DEPRECATED);

