<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto

namespace MediaCloud\Vendor\Google\Protobuf\Internal;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Protobuf\Internal\FileOptions\OptimizeMode instead.
     * @deprecated
     */
    class FileOptions_OptimizeMode {}
}
class_exists(FileOptions\OptimizeMode::class);
@trigger_error('MediaCloud\Vendor\Google\Protobuf\Internal\FileOptions_OptimizeMode is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Protobuf\Internal\FileOptions\OptimizeMode instead', E_USER_DEPRECATED);

