<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1beta1/eval.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1beta1;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBType;
use MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * The state of an evaluation.
 * Can represent an initial, partial, or completed state of evaluation.
 *
 * Generated from protobuf message <code>google.api.expr.v1beta1.EvalState</code>
 */
class EvalState extends \MediaCloud\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The unique values referenced in this message.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     */
    private $values;
    /**
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     */
    private $results;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MediaCloud\Vendor\Google\Api\Expr\V1beta1\ExprValue[]|\Google\Protobuf\Internal\RepeatedField $values
     *           The unique values referenced in this message.
     *     @type \MediaCloud\Vendor\Google\Api\Expr\V1beta1\EvalState\Result[]|\Google\Protobuf\Internal\RepeatedField $results
     *           An ordered list of results.
     *           Tracks the flow of evaluation through the expression.
     *           May be sparse.
     * }
     */
    public function __construct($data = NULL) { \MediaCloud\Vendor\GPBMetadata\Google\Api\Expr\V1Beta1\PBEval::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique values referenced in this message.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * The unique values referenced in this message.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.ExprValue values = 1;</code>
     * @param \MediaCloud\Vendor\Google\Api\Expr\V1beta1\ExprValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Api\Expr\V1beta1\ExprValue::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * An ordered list of results.
     * Tracks the flow of evaluation through the expression.
     * May be sparse.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1beta1.EvalState.Result results = 3;</code>
     * @param \MediaCloud\Vendor\Google\Api\Expr\V1beta1\EvalState\Result[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Api\Expr\V1beta1\EvalState\Result::class);
        $this->results = $arr;

        return $this;
    }

}

