<?php

namespace MediaCloud\Vendor\Aws\SSOAdmin;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Single Sign-On Admin** service.
 * @method \MediaCloud\Vendor\Aws\Result attachManagedPolicyToPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise attachManagedPolicyToPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createAccountAssignment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAccountAssignmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createInstanceAccessControlAttributeConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createInstanceAccessControlAttributeConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAccountAssignment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAccountAssignmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteInlinePolicyFromPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteInlinePolicyFromPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteInstanceAccessControlAttributeConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteInstanceAccessControlAttributeConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deletePermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deletePermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAccountAssignmentCreationStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAccountAssignmentCreationStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAccountAssignmentDeletionStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAccountAssignmentDeletionStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeInstanceAccessControlAttributeConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeInstanceAccessControlAttributeConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describePermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describePermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describePermissionSetProvisioningStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describePermissionSetProvisioningStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result detachManagedPolicyFromPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise detachManagedPolicyFromPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getInlinePolicyForPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getInlinePolicyForPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountAssignmentCreationStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountAssignmentCreationStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountAssignmentDeletionStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountAssignmentDeletionStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountAssignments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountAssignmentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountsForProvisionedPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountsForProvisionedPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listInstances(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listInstancesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listManagedPoliciesInPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listManagedPoliciesInPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPermissionSetProvisioningStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPermissionSetProvisioningStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPermissionSets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPermissionSetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPermissionSetsProvisionedToAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPermissionSetsProvisionedToAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result provisionPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise provisionPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putInlinePolicyToPermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putInlinePolicyToPermissionSetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateInstanceAccessControlAttributeConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateInstanceAccessControlAttributeConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updatePermissionSet(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updatePermissionSetAsync(array $args = [])
 */
class SSOAdminClient extends AwsClient {}
