<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/vision/v1/image_annotator.proto

namespace MediaCloud\Vendor\Google\Cloud\Vision\V1;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBType;
use MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * The response for a single offline file annotation request.
 *
 * Generated from protobuf message <code>google.cloud.vision.v1.AsyncAnnotateFileResponse</code>
 */
class AsyncAnnotateFileResponse extends \MediaCloud\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The output location and metadata from AsyncAnnotateFileRequest.
     *
     * Generated from protobuf field <code>.google.cloud.vision.v1.OutputConfig output_config = 1;</code>
     */
    private $output_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MediaCloud\Vendor\Google\Cloud\Vision\V1\OutputConfig $output_config
     *           The output location and metadata from AsyncAnnotateFileRequest.
     * }
     */
    public function __construct($data = NULL) { \MediaCloud\Vendor\GPBMetadata\Google\Cloud\Vision\V1\ImageAnnotator::initOnce();
        parent::__construct($data);
    }

    /**
     * The output location and metadata from AsyncAnnotateFileRequest.
     *
     * Generated from protobuf field <code>.google.cloud.vision.v1.OutputConfig output_config = 1;</code>
     * @return \MediaCloud\Vendor\Google\Cloud\Vision\V1\OutputConfig|null
     */
    public function getOutputConfig()
    {
        return $this->output_config;
    }

    public function hasOutputConfig()
    {
        return isset($this->output_config);
    }

    public function clearOutputConfig()
    {
        unset($this->output_config);
    }

    /**
     * The output location and metadata from AsyncAnnotateFileRequest.
     *
     * Generated from protobuf field <code>.google.cloud.vision.v1.OutputConfig output_config = 1;</code>
     * @param \MediaCloud\Vendor\Google\Cloud\Vision\V1\OutputConfig $var
     * @return $this
     */
    public function setOutputConfig($var)
    {
        GPBUtil::checkMessage($var, \MediaCloud\Vendor\Google\Cloud\Vision\V1\OutputConfig::class);
        $this->output_config = $var;

        return $this;
    }

}

