<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/vision/v1/image_annotator.proto

namespace MediaCloud\Vendor\Google\Cloud\Vision\V1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Cloud\Vision\V1\FaceAnnotation\Landmark instead.
     * @deprecated
     */
    class FaceAnnotation_Landmark {}
}
class_exists(FaceAnnotation\Landmark::class);
@trigger_error('MediaCloud\Vendor\Google\Cloud\Vision\V1\FaceAnnotation_Landmark is deprecated and will be removed in a future release. Use MediaCloud\Vendor\Google\Cloud\Vision\V1\FaceAnnotation\Landmark instead', E_USER_DEPRECATED);

