<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/vision/v1/product_search_service.proto

namespace MediaCloud\Vendor\Google\Cloud\Vision\V1;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBType;
use MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for the `ImportProductSets` method.
 * This message is returned by the
 * [google.longrunning.Operations.GetOperation][google.longrunning.Operations.GetOperation] method in the returned
 * [google.longrunning.Operation.response][google.longrunning.Operation.response] field.
 *
 * Generated from protobuf message <code>google.cloud.vision.v1.ImportProductSetsResponse</code>
 */
class ImportProductSetsResponse extends \MediaCloud\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The list of reference_images that are imported successfully.
     *
     * Generated from protobuf field <code>repeated .google.cloud.vision.v1.ReferenceImage reference_images = 1;</code>
     */
    private $reference_images;
    /**
     * The rpc status for each ImportProductSet request, including both successes
     * and errors.
     * The number of statuses here matches the number of lines in the csv file,
     * and statuses[i] stores the success or failure status of processing the i-th
     * line of the csv, starting from line 0.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 2;</code>
     */
    private $statuses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MediaCloud\Vendor\Google\Cloud\Vision\V1\ReferenceImage[]|\Google\Protobuf\Internal\RepeatedField $reference_images
     *           The list of reference_images that are imported successfully.
     *     @type \MediaCloud\Vendor\Google\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $statuses
     *           The rpc status for each ImportProductSet request, including both successes
     *           and errors.
     *           The number of statuses here matches the number of lines in the csv file,
     *           and statuses[i] stores the success or failure status of processing the i-th
     *           line of the csv, starting from line 0.
     * }
     */
    public function __construct($data = NULL) { \MediaCloud\Vendor\GPBMetadata\Google\Cloud\Vision\V1\ProductSearchService::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of reference_images that are imported successfully.
     *
     * Generated from protobuf field <code>repeated .google.cloud.vision.v1.ReferenceImage reference_images = 1;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getReferenceImages()
    {
        return $this->reference_images;
    }

    /**
     * The list of reference_images that are imported successfully.
     *
     * Generated from protobuf field <code>repeated .google.cloud.vision.v1.ReferenceImage reference_images = 1;</code>
     * @param \MediaCloud\Vendor\Google\Cloud\Vision\V1\ReferenceImage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReferenceImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Cloud\Vision\V1\ReferenceImage::class);
        $this->reference_images = $arr;

        return $this;
    }

    /**
     * The rpc status for each ImportProductSet request, including both successes
     * and errors.
     * The number of statuses here matches the number of lines in the csv file,
     * and statuses[i] stores the success or failure status of processing the i-th
     * line of the csv, starting from line 0.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 2;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getStatuses()
    {
        return $this->statuses;
    }

    /**
     * The rpc status for each ImportProductSet request, including both successes
     * and errors.
     * The number of statuses here matches the number of lines in the csv file,
     * and statuses[i] stores the success or failure status of processing the i-th
     * line of the csv, starting from line 0.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 2;</code>
     * @param \MediaCloud\Vendor\Google\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatuses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Rpc\Status::class);
        $this->statuses = $arr;

        return $this;
    }

}

