<?php

namespace MediaCloud\Vendor\Aws\Outposts;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Outposts** service.
 * @method \MediaCloud\Vendor\Aws\Result cancelOrder(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cancelOrderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createOrder(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createOrderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createOutpost(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createOutpostAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSite(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSiteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteOutpost(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteOutpostAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSite(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSiteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getCatalogItem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getCatalogItemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getOrder(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getOrderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getOutpost(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getOutpostAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getOutpostInstanceTypes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getOutpostInstanceTypesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getSite(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSiteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getSiteAddress(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSiteAddressAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCatalogItems(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCatalogItemsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listOrders(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listOrdersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listOutposts(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listOutpostsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSites(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSitesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateOutpost(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateOutpostAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSite(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSiteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSiteAddress(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSiteAddressAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSiteRackPhysicalProperties(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSiteRackPhysicalPropertiesAsync(array $args = [])
 */
class OutpostsClient extends AwsClient {}
