<?php

namespace MediaCloud\Vendor\Aws\CodeGuruProfiler;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon CodeGuru Profiler** service.
 * @method \MediaCloud\Vendor\Aws\Result addNotificationChannels(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise addNotificationChannelsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchGetFrameMetricData(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchGetFrameMetricDataAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result configureAgent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise configureAgentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createProfilingGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createProfilingGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProfilingGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProfilingGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeProfilingGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeProfilingGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getFindingsReportAccountSummary(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getFindingsReportAccountSummaryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getNotificationConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getNotificationConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listFindingsReports(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listFindingsReportsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProfileTimes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProfileTimesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProfilingGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProfilingGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result postAgentProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise postAgentProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putPermission(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putPermissionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeNotificationChannel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeNotificationChannelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removePermission(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removePermissionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result submitFeedback(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise submitFeedbackAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateProfilingGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateProfilingGroupAsync(array $args = [])
 */
class CodeGuruProfilerClient extends AwsClient {}
