<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/distribution.proto

namespace MediaCloud\Vendor\Google\Api;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Distribution\Exemplar instead.
     * @deprecated
     */
    class Distribution_Exemplar {}
}
class_exists(Distribution\Exemplar::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Distribution_Exemplar is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Distribution\Exemplar instead', E_USER_DEPRECATED);

