<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/distribution.proto

namespace MediaCloud\Vendor\Google\Api;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Distribution\BucketOptions\Explicit instead.
     * @deprecated
     */
    class Distribution_BucketOptions_Explicit {}
}
class_exists(Distribution\BucketOptions\Explicit::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Distribution_BucketOptions_Explicit is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Distribution\BucketOptions\Explicit instead', E_USER_DEPRECATED);

