<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/label.proto

namespace MediaCloud\Vendor\Google\Api;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\LabelDescriptor\ValueType instead.
     * @deprecated
     */
    class LabelDescriptor_ValueType {}
}
class_exists(LabelDescriptor\ValueType::class);
@trigger_error('MediaCloud\Vendor\Google\Api\LabelDescriptor_ValueType is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\LabelDescriptor\ValueType instead', E_USER_DEPRECATED);

