<?php

namespace MediaCloud\Vendor\Aws\AppRunner;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS App Runner** service.
 * @method \MediaCloud\Vendor\Aws\Result associateCustomDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateCustomDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createAutoScalingConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAutoScalingConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createConnection(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createConnectionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createVpcConnector(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createVpcConnectorAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAutoScalingConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAutoScalingConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteConnection(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteConnectionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteVpcConnector(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteVpcConnectorAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAutoScalingConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAutoScalingConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeCustomDomains(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeCustomDomainsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeVpcConnector(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeVpcConnectorAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateCustomDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateCustomDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAutoScalingConfigurations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAutoScalingConfigurationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listConnections(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listConnectionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listOperations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listOperationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listServices(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listServicesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listVpcConnectors(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listVpcConnectorsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result pauseService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise pauseServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result resumeService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise resumeServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startDeployment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startDeploymentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateServiceAsync(array $args = [])
 */
class AppRunnerClient extends AwsClient {}
