<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/v1/policy.proto

namespace MediaCloud\Vendor\Google\Cloud\Iam\V1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Cloud\Iam\V1\AuditConfigDelta\Action instead.
     * @deprecated
     */
    class AuditConfigDelta_Action {}
}
class_exists(AuditConfigDelta\Action::class);
@trigger_error('MediaCloud\Vendor\Google\Cloud\Iam\V1\AuditConfigDelta_Action is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Cloud\Iam\V1\AuditConfigDelta\Action instead', E_USER_DEPRECATED);

