<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/checked.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBType;
use MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * Function type with result and arg types.
 *
 * Generated from protobuf message <code>google.api.expr.v1alpha1.Type.FunctionType</code>
 */
class FunctionType extends \MediaCloud\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * Result type of the function.
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.Type result_type = 1;</code>
     */
    private $result_type = null;
    /**
     * Argument types of the function.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Type arg_types = 2;</code>
     */
    private $arg_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type $result_type
     *           Result type of the function.
     *     @type \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type[]|\Google\Protobuf\Internal\RepeatedField $arg_types
     *           Argument types of the function.
     * }
     */
    public function __construct($data = NULL) { \MediaCloud\Vendor\GPBMetadata\Google\Api\Expr\V1Alpha1\Checked::initOnce();
        parent::__construct($data);
    }

    /**
     * Result type of the function.
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.Type result_type = 1;</code>
     * @return \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type
     */
    public function getResultType()
    {
        return $this->result_type;
    }

    /**
     * Result type of the function.
     *
     * Generated from protobuf field <code>.google.api.expr.v1alpha1.Type result_type = 1;</code>
     * @param \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type $var
     * @return $this
     */
    public function setResultType($var)
    {
        GPBUtil::checkMessage($var, \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type::class);
        $this->result_type = $var;

        return $this;
    }

    /**
     * Argument types of the function.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Type arg_types = 2;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getArgTypes()
    {
        return $this->arg_types;
    }

    /**
     * Argument types of the function.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Type arg_types = 2;</code>
     * @param \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type::class);
        $this->arg_types = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FunctionType::class, \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type_FunctionType::class);

