<?php

namespace MediaCloud\Vendor\Aws\AmplifyBackend;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AmplifyBackend** service.
 * @method \MediaCloud\Vendor\Aws\Result cloneBackend(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cloneBackendAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackend(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackendAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackendAPI(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackendAPIAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackendAuth(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackendAuthAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackendConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackendConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBackendStorage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBackendStorageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createToken(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createTokenAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBackend(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBackendAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBackendAPI(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBackendAPIAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBackendAuth(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBackendAuthAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBackendStorage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBackendStorageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteToken(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteTokenAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result generateBackendAPIModels(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise generateBackendAPIModelsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackend(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackendAPI(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendAPIAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackendAPIModels(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendAPIModelsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackendAuth(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendAuthAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackendJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBackendStorage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBackendStorageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getToken(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getTokenAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result importBackendAuth(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise importBackendAuthAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result importBackendStorage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise importBackendStorageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listBackendJobs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listBackendJobsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listS3Buckets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listS3BucketsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeAllBackends(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeAllBackendsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeBackendConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeBackendConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBackendAPI(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBackendAPIAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBackendAuth(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBackendAuthAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBackendConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBackendConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBackendJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBackendJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBackendStorage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBackendStorageAsync(array $args = [])
 */
class AmplifyBackendClient extends AwsClient {}
