<?php

namespace MediaCloud\Vendor\Aws\GlueDataBrew;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Glue DataBrew** service.
 * @method \MediaCloud\Vendor\Aws\Result batchDeleteRecipeVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchDeleteRecipeVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createProfileJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createProfileJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createProject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createProjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRecipe(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRecipeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRecipeJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRecipeJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRuleset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRulesetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSchedule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createScheduleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRecipeVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRecipeVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRuleset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRulesetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSchedule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteScheduleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeJobRun(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeJobRunAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeProject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeProjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeRecipe(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeRecipeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeRuleset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeRulesetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSchedule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeScheduleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDatasets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDatasetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listJobRuns(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listJobRunsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listJobs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listJobsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProjects(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProjectsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRecipeVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRecipeVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRecipes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRecipesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRulesets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRulesetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSchedules(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSchedulesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result publishRecipe(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise publishRecipeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result sendProjectSessionAction(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise sendProjectSessionActionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startJobRun(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startJobRunAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startProjectSession(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startProjectSessionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopJobRun(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopJobRunAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDataset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDatasetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateProfileJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateProfileJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateProject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateProjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRecipe(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRecipeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRecipeJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRecipeJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRuleset(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRulesetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSchedule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateScheduleAsync(array $args = [])
 */
class GlueDataBrewClient extends AwsClient {}
