<?php
// Copyright (c) 2016 Interfacelab LLC. All rights reserved.
//
// Released under the GPLv3 license
// http://www.gnu.org/licenses/gpl-3.0.html
//
// **********************************************************************
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// **********************************************************************

if (!defined('ABSPATH')) { header('Location: /'); die; }

return [
	"3.0.0" => [
		"copy" => [
			"ilab-media-s3-bucket" => "ilab-media-google-bucket"
		],
		"transition" => [
			'ilab-media-s3-rekognition-detect-labels' => 'ilab-vision-detect-labels',
			'ilab-media-s3-rekognition-detect-labels-tax' => 'ilab-vision-detect-labels-tax',
			'ilab-media-s3-rekognition-detect-labels-confidence' => 'ilab-vision-detect-labels-confidence',
			'ilab-media-s3-rekognition-detect-moderation-labels' => 'ilab-vision-detect-moderation-labels',
			'ilab-media-s3-rekognition-detect-moderation-labels-tax' => 'ilab-vision-detect-moderation-labels-tax',
			'ilab-media-s3-rekognition-detect-moderation-labels-confidence' => 'ilab-vision-detect-moderation-labels-confidence',
			'ilab-media-s3-rekognition-detect-celebrity' => 'ilab-vision-detect-celebrity',
			'ilab-media-s3-rekognition-detect-celebrity-tax' => 'ilab-vision-detect-celebrity-tax',
			'ilab-media-s3-rekognition-detect-faces' => 'ilab-vision-detect-faces',
			'ilab-media-s3-rekognition-ignored-tags' => 'ilab-vision-ignored-tags',

		],
	],
	"3.0.1" => [
		"copy" => [
		],
		"transition" => [
			'ilab-assets-cache-control' => 'mcloud-assets-cache-control',
			'ilab-assets-cdn-base' => 'mcloud-assets-cdn-base',
			'ilab-assets-expires' => 'mcloud-assets-expires',
			'ilab-assets-log-warnings' => 'mcloud-assets-log-warnings',
			'ilab-assets-process-live' => 'mcloud-assets-process-live',
			'ilab-assets-store-css' => 'mcloud-assets-store-css',
			'ilab-assets-store-js' => 'mcloud-assets-store-js',
			'ilab-assets-use-build-version' => 'mcloud-assets-use-build-version',
			'ilab-media-crop-quality' => 'mcloud-crop-quality',
			'ilab-media-s3-debug-logging-level' => 'mcloud-debug-logging-level',
			'ilab-media-s3-debug-max-database-entries' => 'mcloud-debug-max-database-entries',
			'ilab-media-direct-uploads-detect-faces' => 'mcloud-direct-uploads-detect-faces',
			'ilab-media-direct-uploads-integration' => 'mcloud-direct-uploads-integration',
			'ilab-media-direct-uploads-simultaneous-uploads' => 'mcloud-direct-uploads-simultaneous-uploads',
			'ilab-media-cloud-edd-presigned-expiration' => 'mcloud-edd-presigned-expiration',
			'ilab-media-cloud-edd-use-presigned-urls' => 'mcloud-edd-use-presigned-urls',
			'ilab-media-glide-cache-remote' => 'mcloud-glide-cache-remote',
			'ilab-media-glide-cache-ttl' => 'mcloud-glide-cache-ttl',
			'ilab-media-glide-cdn' => 'mcloud-glide-cdn',
			'ilab-media-glide-convert-png' => 'mcloud-glide-convert-png',
			'ilab-media-glide-default-quality' => 'mcloud-glide-default-quality',
			'ilab-media-glide-generate-thumbnails' => 'mcloud-glide-generate-thumbnails',
			'ilab-media-glide-image-path' => 'mcloud-glide-image-path',
			'ilab-media-glide-max-size' => 'mcloud-glide-max-size',
			'ilab-media-glide-progressive-jpeg' => 'mcloud-glide-progressive-jpeg',
			'ilab-media-glide-signing-key' => 'mcloud-glide-signing-key',
			'ilab-google-settings-error' => 'mcloud-google-settings-error',
			'ilab-media-imgix-auto-compress' => 'mcloud-imgix-auto-compress',
			'ilab-media-imgix-auto-format' => 'mcloud-imgix-auto-format',
			'ilab-media-imgix-default-quality' => 'mcloud-imgix-default-quality',
			'ilab-media-imgix-detect-faces' => 'mcloud-imgix-detect-faces',
			'ilab-media-imgix-domains' => 'mcloud-imgix-domains',
			'ilab-media-imgix-enable-alt-formats' => 'mcloud-imgix-enable-alt-formats',
			'ilab-media-imgix-enable-gifs' => 'mcloud-imgix-enable-gifs',
			'ilab-media-imgix-generate-thumbnails' => 'mcloud-imgix-generate-thumbnails',
			'ilab-media-imgix-no-gif-sizes' => 'mcloud-imgix-no-gif-sizes',
			'ilab-media-imgix-render-pdf-files' => 'mcloud-imgix-render-pdf-files',
			'ilab-media-imgix-signing-key' => 'mcloud-imgix-signing-key',
			'ilab-media-imgix-skip-gifs' => 'mcloud-imgix-skip-gifs',
			'ilab-media-imgix-use-https' => 'mcloud-imgix-use-https',
			'ilab-mc-master-slider-image-height' => 'mcloud-master-slider-image-height',
			'ilab-mc-master-slider-image-resize' => 'mcloud-master-slider-image-resize',
			'ilab-mc-master-slider-image-width' => 'mcloud-master-slider-image-width',
			'ilab-mc-master-slider-thumb-crop' => 'mcloud-master-slider-thumb-crop',
			'ilab-mc-master-slider-thumb-height' => 'mcloud-master-slider-thumb-height',
			'ilab-mc-master-slider-thumb-width' => 'mcloud-master-slider-thumb-width',
			'media-cloud-network-browser-allow-deleting' => 'mcloud-network-browser-allow-deleting',
			'media-cloud-network-browser-allow-uploads' => 'mcloud-network-browser-allow-uploads',
			'media-cloud-network-browser-hide' => 'mcloud-network-browser-hide',
			'media-cloud-network-browser-lock-to-root' => 'mcloud-network-browser-lock-to-root',
			'media-cloud-network-hide-batch' => 'mcloud-network-hide-batch',
			'ilab_media_cloud_network_mode' => 'mcloud-network-mode',
			'ilab-mc-ngg-use-url-cache' => 'mcloud-ngg-use-url-cache',
			'ilab-media-cloud-pinned-tools' => 'mcloud-pinned-tools',
			'ilab-mc-smart-slider-path-prefix' => 'mcloud-smart-slider-path-prefix',
			'ilab-media-backblaze-account-id' => 'mcloud-storage-backblaze-account-id',
			'ilab-media-backblaze-bucket-url' => 'mcloud-storage-backblaze-bucket-url',
			'ilab-media-backblaze-key' => 'mcloud-storage-backblaze-key',
			'ilab-media-s3-batch-background-processing' => 'mcloud-storage-batch-background-processing',
			'ilab-media-s3-batch-connect-timeout' => 'mcloud-storage-batch-connect-timeout',
			'ilab-media-s3-batch-skip-dns' => 'mcloud-storage-batch-skip-dns',
			'ilab-media-s3-batch-timeout' => 'mcloud-storage-batch-timeout',
			'ilab-media-s3-batch-verify-ssl' => 'mcloud-storage-batch-verify-ssl',
			'ilab-media-s3-cache-control' => 'mcloud-storage-cache-control',
			'ilab-media-s3-cdn-base' => 'mcloud-storage-cdn-base',
			'ilab-media-s3-delete-from-s3' => 'mcloud-storage-delete-from-server',
			'ilab-media-s3-delete-uploads' => 'mcloud-storage-delete-uploads',
			'ilab-media-s3-display-s3-badge' => 'mcloud-storage-display-badge',
			'ilab-cloud-storage-display-media-list' => 'mcloud-storage-display-media-list',
			'ilab-doc-s3-cdn-base' => 'mcloud-storage-doc-cdn-base',
			'ilab-media-s3-expires' => 'mcloud-storage-expires',
			'ilab-media-google-bucket' => 'mcloud-storage-google-bucket',
			'ilab-media-google-credentials' => 'mcloud-storage-google-credentials',
			'ilab-media-s3-ignored-mime-types' => 'mcloud-storage-ignored-mime-types',
			'ilab-media-s3-prefix' => 'mcloud-storage-prefix',
			'ilab-media-s3-presigned-expiration' => 'mcloud-storage-presigned-expiration',
			'ilab-media-s3-privacy' => 'mcloud-storage-privacy',
			'ilab-media-storage-provider' => 'mcloud-storage-provider',
			'ilab-media-s3-access-key' => 'mcloud-storage-s3-access-key',
			'ilab-media-s3-bucket' => 'mcloud-storage-s3-bucket',
			'ilab-media-s3-credential-provider' => 'mcloud-storage-s3-use-credential-provider',
			'ilab-media-s3-endpoint' => 'mcloud-storage-s3-endpoint',
			'ilab-media-s3-region' => 'mcloud-storage-s3-region',
			'ilab-media-s3-secret' => 'mcloud-storage-s3-secret',
			'ilab-media-s3-use-path-style-endpoint' => 'mcloud-storage-s3-use-path-style-endpoint',
			'ilab-media-s3-use-transfer-acceleration' => 'mcloud-storage-s3-use-transfer-acceleration',
			'ilab-media-s3-upload-documents' => 'mcloud-storage-upload-documents',
			'ilab-media-s3-use-presigned-urls' => 'mcloud-storage-use-presigned-urls',
			'ilab-media-tool-enabled-assets' => 'mcloud-tool-enabled-assets',
			'ilab-media-tool-enabled-batch-processing' => 'mcloud-tool-enabled-batch-processing',
			'ilab-media-tool-enabled-browser' => 'mcloud-tool-enabled-browser',
			'ilab-media-tool-enabled-crop' => 'mcloud-tool-enabled-crop',
			'ilab-media-tool-enabled-debugging' => 'mcloud-tool-enabled-debugging',
			'ilab-media-tool-enabled-glide' => 'mcloud-tool-enabled-glide',
			'ilab-media-tool-enabled-image-sizes' => 'mcloud-tool-enabled-image-sizes',
			'ilab-media-tool-enabled-imgix' => 'mcloud-tool-enabled-imgix',
			'ilab-media-tool-enabled-integrations' => 'mcloud-tool-enabled-integrations',
			'ilab-media-tool-enabled-media-upload' => 'mcloud-tool-enabled-media-upload',
			'ilab-media-tool-enabled-presets' => 'mcloud-tool-enabled-presets',
			'ilab-media-tool-enabled-rekognition' => 'mcloud-tool-enabled-rekognition',
			'ilab-media-tool-enabled-storage' => 'mcloud-tool-enabled-storage',
			'ilab-media-tool-enabled-troubleshooting' => 'mcloud-tool-enabled-troubleshooting',
			'ilab-media-tool-enabled-vision' => 'mcloud-tool-enabled-vision',
			'ilab-vision-always-background' => 'mcloud-vision-always-background',
			'ilab-vision-detect-celebrity' => 'mcloud-vision-detect-celebrity',
			'ilab-vision-detect-celebrity-tax' => 'mcloud-vision-detect-celebrity-tax',
			'ilab-vision-detect-faces' => 'mcloud-vision-detect-faces',
			'ilab-vision-detect-labels' => 'mcloud-vision-detect-labels',
			'ilab-vision-detect-labels-confidence' => 'mcloud-vision-detect-labels-confidence',
			'ilab-vision-detect-labels-tax' => 'mcloud-vision-detect-labels-tax',
			'ilab-vision-detect-moderation-labels' => 'mcloud-vision-detect-moderation-labels',
			'ilab-vision-detect-moderation-labels-confidence' => 'mcloud-vision-detect-moderation-labels-confidence',
			'ilab-vision-detect-moderation-labels-tax' => 'mcloud-vision-detect-moderation-labels-tax',
			'ilab-media-vision-ignored-tags' => 'mcloud-vision-ignored-tags',
			'ilab-vision-ignored-tags' => 'mcloud-vision-ignored-tags',
			'ilab-vision-provider' => 'mcloud-vision-provider',
			'ilab-media-cloud-woo-commerce-presigned-expiration' => 'mcloud-woo-commerce-presigned-expiration',
			'ilab-media-cloud-woo-commerce-use-presigned-urls' => 'mcloud-woo-commerce-use-presigned-urls',
		],
		"deprecated" => [
			'ILAB_AWS_REKOGNITION_DETECT_LABELS' => 'MCLOUD_VISION_DETECT_LABELS',
			'ILAB_AWS_REKOGNITION_DETECT_LABELS_TAX' => 'MCLOUD_VISION_DETECT_LABELS_TAX',
			'ILAB_AWS_REKOGNITION_DETECT_LABELS_CONFIDENCE' => 'MCLOUD_VISION_DETECT_LABELS_CONFIDENCE',
			'ILAB_AWS_REKOGNITION_MODERATION_LABELS' => 'MCLOUD_VISION_DETECT_MODERATION_LABELS',
			'ILAB_AWS_REKOGNITION_MODERATION_LABELS_TAX' => 'MCLOUD_VISION_DETECT_MODERATION_LABELS_TAX',
			'ILAB_AWS_REKOGNITION_MODERATION_LABELS_CONFIDENCE' => 'MCLOUD_VISION_DETECT_MODERATION_LABELS_CONFIDENCE',
			'ILAB_AWS_REKOGNITION_DETECT_CELEBRITY' => 'MCLOUD_VISION_DETECT_CELEBRITY',
			'ILAB_AWS_REKOGNITION_DETECT_CELEBRITY_TAX' => 'MCLOUD_VISION_DETECT_CELEBRITY_TAX',
			'ILAB_AWS_REKOGNITION_DETECT_FACES' => 'MCLOUD_VISION_DETECT_FACES',
			'ILAB_AWS_S3_CACHE_CONTROL' => 'MCLOUD_STORAGE_CACHE_CONTROL',
			'ILAB_AWS_S3_CDN_BASE' => 'MCLOUD_STORAGE_CDN_BASE',
			'ILAB_AWS_S3_DOC_CDN_BASE' => 'MCLOUD_STORAGE_DOC_CDN_BASE',
			'ILAB_AWS_S3_EXPIRES' => 'MCLOUD_STORAGE_EXPIRES',
			'ILAB_CLOUD_GOOGLE_BUCKET' => 'MCLOUD_STORAGE_GOOGLE_BUCKET',
			'ILAB_AWS_S3_BUCKET' => 'MCLOUD_STORAGE_S3_BUCKET',
			'ILAB_CLOUD_BUCKET' => 'MCLOUD_STORAGE_S3_BUCKET',
			'ILAB_CLOUD_STORAGE_PROVIDER' => 'MCLOUD_STORAGE_PROVIDER',
			'ILAB_AWS_S3_ACCESS_KEY' => 'MCLOUD_STORAGE_S3_ACCESS_KEY',
			'ILAB_CLOUD_ACCESS_KEY' => 'MCLOUD_STORAGE_S3_ACCESS_KEY',
			'ILAB_AWS_S3_ENDPOINT' => 'MCLOUD_STORAGE_S3_ENDPOINT',
			'ILAB_CLOUD_ENDPOINT' => 'MCLOUD_STORAGE_S3_ENDPOINT',
			'ILAB_AWS_S3_REGION' => 'MCLOUD_STORAGE_S3_REGION',
			'ILAB_CLOUD_REGION' => 'MCLOUD_STORAGE_S3_REGION',
			'ILAB_AWS_S3_ACCESS_SECRET' => 'MCLOUD_STORAGE_S3_SECRET',
			'ILAB_CLOUD_ACCESS_SECRET' => 'MCLOUD_STORAGE_S3_SECRET',
			'ILAB_AWS_S3_ENDPOINT_PATH_STYLE' => 'MCLOUD_STORAGE_S3_USE_PATH_STYLE_ENDPOINT',
			'ILAB_CLOUD_ENDPOINT_PATH_STYLE' => 'MCLOUD_STORAGE_S3_USE_PATH_STYLE_ENDPOINT',
			'ILAB_AWS_S3_TRANSFER_ACCELERATION' => 'MCLOUD_STORAGE_S3_SECRET',
			'ILAB_MEDIA_DEBUGGING_ENABLED' => 'MCLOUD_TOOL_ENABLED_DEBUGGING',
			'ILAB_VISION_PROVIDER' => 'MCLOUD_VISION_PROVIDER',
			'ILAB_CLOUD_GOOGLE_CREDENTIALS' => 'MCLOUD_STORAGE_GOOGLE_CREDENTIALS_FILE',
			'ILAB_MEDIA_CLOUD_VIEW_CACHE' => 'MCLOUD_VIEW_CACHE',
			'ILAB_AWS_S3_USE_CREDENTIAL_PROVIDER' => 'MCLOUD_STORAGE_S3_USE_CREDENTIAL_PROVIDER',
			'ILAB_CLOUD_USE_CREDENTIAL_PROVIDER' => 'MCLOUD_STORAGE_S3_USE_CREDENTIAL_PROVIDER'
		],
	],
];
