<?php

namespace MediaCloud\Vendor\Aws\ConnectWisdomService;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Connect Wisdom Service** service.
 * @method \MediaCloud\Vendor\Aws\Result createAssistant(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAssistantAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createAssistantAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAssistantAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createContent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createContentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createKnowledgeBase(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createKnowledgeBaseAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSession(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSessionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAssistant(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAssistantAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAssistantAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAssistantAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteContent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteContentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteKnowledgeBase(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteKnowledgeBaseAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAssistant(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAssistantAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAssistantAssociation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAssistantAssociationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getContent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getContentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getContentSummary(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getContentSummaryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getKnowledgeBase(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getKnowledgeBaseAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getSession(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSessionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAssistantAssociations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAssistantAssociationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAssistants(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAssistantsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listContents(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listContentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listKnowledgeBases(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listKnowledgeBasesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result notifyRecommendationsReceived(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise notifyRecommendationsReceivedAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result queryAssistant(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise queryAssistantAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeKnowledgeBaseTemplateUri(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeKnowledgeBaseTemplateUriAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result searchContent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise searchContentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result searchSessions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise searchSessionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startContentUpload(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startContentUploadAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateContent(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateContentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateKnowledgeBaseTemplateUri(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateKnowledgeBaseTemplateUriAsync(array $args = [])
 */
class ConnectWisdomServiceClient extends AwsClient {}
