<?php

namespace MediaCloud\Vendor\Aws\CustomerProfiles;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Connect Customer Profiles** service.
 * @method \MediaCloud\Vendor\Aws\Result addProfileKey(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise addProfileKeyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createIntegrationWorkflow(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createIntegrationWorkflowAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteIntegration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteIntegrationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProfileKey(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProfileKeyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProfileObject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProfileObjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProfileObjectType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProfileObjectTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteWorkflow(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteWorkflowAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAutoMergingPreview(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAutoMergingPreviewAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getIdentityResolutionJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getIdentityResolutionJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getIntegration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getIntegrationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMatches(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMatchesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getProfileObjectType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getProfileObjectTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getProfileObjectTypeTemplate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getProfileObjectTypeTemplateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getWorkflow(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getWorkflowAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getWorkflowSteps(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getWorkflowStepsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountIntegrations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountIntegrationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDomains(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDomainsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listIdentityResolutionJobs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listIdentityResolutionJobsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listIntegrations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listIntegrationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProfileObjectTypeTemplates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProfileObjectTypeTemplatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProfileObjectTypes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProfileObjectTypesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProfileObjects(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProfileObjectsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listWorkflows(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listWorkflowsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result mergeProfiles(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise mergeProfilesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putIntegration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putIntegrationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putProfileObject(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putProfileObjectAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putProfileObjectType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putProfileObjectTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result searchProfiles(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise searchProfilesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDomain(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDomainAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateProfileAsync(array $args = [])
 */
class CustomerProfilesClient extends AwsClient {}
