<?php

namespace MediaCloud\Vendor\Aws\kendra;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWSKendraFrontendService** service.
 * @method \MediaCloud\Vendor\Aws\Result batchDeleteDocument(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchDeleteDocumentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchPutDocument(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchPutDocumentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDataSource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDataSourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFaq(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFaqAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createIndex(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createIndexAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDataSource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDataSourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteFaq(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteFaqAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteIndex(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteIndexAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDataSource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDataSourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeFaq(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeFaqAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeIndex(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeIndexAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDataSourceSyncJobs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDataSourceSyncJobsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDataSources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDataSourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listFaqs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listFaqsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listIndices(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listIndicesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result query(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise queryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startDataSourceSyncJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startDataSourceSyncJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result stopDataSourceSyncJob(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise stopDataSourceSyncJobAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result submitFeedback(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise submitFeedbackAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateDataSource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateDataSourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateIndex(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateIndexAsync(array $args = [])
 */
class kendraClient extends AwsClient {}
