<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/rpc/status.proto

namespace MediaCloud\Vendor\GPBMetadata\Google\Rpc;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \MediaCloud\Vendor\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        } \MediaCloud\Vendor\GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            '
à
google/rpc/status.proto
google.rpc"N
Status
code (
message (	%
details (2.google.protobuf.AnyBa
com.google.rpcBStatusProtoPZ7google.golang.org/genproto/googleapis/rpc/status;statusø¢RPCbproto3'
        , true);

        static::$is_initialized = true;
    }
}
