<?php

namespace MediaCloud\Vendor\Aws\MigrationHubRefactorSpaces;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Migration Hub Refactor Spaces** service.
 * @method \MediaCloud\Vendor\Aws\Result createApplication(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createApplicationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createEnvironment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createEnvironmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRoute(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRouteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteApplication(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteEnvironment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteEnvironmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRoute(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRouteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getApplication(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getApplicationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getEnvironment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getEnvironmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getRoute(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getRouteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getService(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getServiceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listApplications(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listApplicationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listEnvironmentVpcs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listEnvironmentVpcsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listEnvironments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listEnvironmentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRoutes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRoutesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listServices(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listServicesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putResourcePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putResourcePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 */
class MigrationHubRefactorSpacesClient extends AwsClient {}
