<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/servicemanager.proto

namespace MediaCloud\Vendor\Google\Cloud\ServiceManagement\V1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Cloud\ServiceManagement\V1\GetServiceConfigRequest\ConfigView instead.
     * @deprecated
     */
    class GetServiceConfigRequest_ConfigView {}
}
class_exists(GetServiceConfigRequest\ConfigView::class);
@trigger_error('MediaCloud\Vendor\Google\Cloud\ServiceManagement\V1\GetServiceConfigRequest_ConfigView is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Cloud\ServiceManagement\V1\GetServiceConfigRequest\ConfigView instead', E_USER_DEPRECATED);

