<?php

namespace MediaCloud\Vendor\Aws\WorkSpacesWeb;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon WorkSpaces Web** service.
 * @method \MediaCloud\Vendor\Aws\Result associateBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createIdentityProvider(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createIdentityProviderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createPortal(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createPortalAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteIdentityProvider(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteIdentityProviderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deletePortal(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deletePortalAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getIdentityProvider(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getIdentityProviderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPortal(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPortalAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPortalServiceProviderMetadata(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPortalServiceProviderMetadataAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getTrustStoreCertificate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getTrustStoreCertificateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listIdentityProviders(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listIdentityProvidersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPortals(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPortalsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTrustStoreCertificates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTrustStoreCertificatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTrustStores(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTrustStoresAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listUserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateBrowserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateBrowserSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateIdentityProvider(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateIdentityProviderAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateNetworkSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateNetworkSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updatePortal(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updatePortalAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateTrustStore(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateTrustStoreAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateUserSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateUserSettingsAsync(array $args = [])
 */
class WorkSpacesWebClient extends AwsClient {}
