<?php

namespace MediaCloud\Vendor\Aws\Route53RecoveryControlConfig;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Route53 Recovery Control Config** service.
 * @method \MediaCloud\Vendor\Aws\Result createCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createControlPanel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createControlPanelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRoutingControl(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRoutingControlAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSafetyRule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSafetyRuleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteControlPanel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteControlPanelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRoutingControl(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRoutingControlAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSafetyRule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSafetyRuleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeControlPanel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeControlPanelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeRoutingControl(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeRoutingControlAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSafetyRule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSafetyRuleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAssociatedRoute53HealthChecks(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAssociatedRoute53HealthChecksAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listClusters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listClustersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listControlPanels(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listControlPanelsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRoutingControls(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRoutingControlsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSafetyRules(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSafetyRulesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateControlPanel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateControlPanelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateRoutingControl(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateRoutingControlAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSafetyRule(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSafetyRuleAsync(array $args = [])
 */
class Route53RecoveryControlConfigClient extends AwsClient {}
