<?php

namespace MediaCloud\Vendor\Aws\Inspector2;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Inspector2** service.
 * @method \MediaCloud\Vendor\Aws\Result associateMember(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateMemberAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchGetAccountStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchGetAccountStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result batchGetFreeTrialInfo(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchGetFreeTrialInfoAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result cancelFindingsReport(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cancelFindingsReportAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFilter(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFilterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFindingsReport(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFindingsReportAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteFilter(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteFilterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeOrganizationConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeOrganizationConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disable(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disableAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disableDelegatedAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disableDelegatedAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateMember(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateMemberAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result enable(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise enableAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result enableDelegatedAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise enableDelegatedAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getDelegatedAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getDelegatedAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getFindingsReportStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getFindingsReportStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMember(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMemberAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAccountPermissions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAccountPermissionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCoverage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCoverageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listCoverageStatistics(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listCoverageStatisticsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDelegatedAdminAccounts(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDelegatedAdminAccountsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listFilters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listFiltersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listFindingAggregations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listFindingAggregationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listFindings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listFindingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listMembers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listMembersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listUsageTotals(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listUsageTotalsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateFilter(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateFilterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateOrganizationConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateOrganizationConfigurationAsync(array $args = [])
 */
class Inspector2Client extends AwsClient {}
