<?php

namespace MediaCloud\Vendor\Aws\RAM;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Resource Access Manager** service.
 * @method \MediaCloud\Vendor\Aws\Result acceptResourceShareInvitation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise acceptResourceShareInvitationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateResourceShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateResourceShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateResourceSharePermission(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateResourceSharePermissionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createResourceShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createResourceShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteResourceShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteResourceShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateResourceShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateResourceShareAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateResourceSharePermission(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateResourceSharePermissionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result enableSharingWithAwsOrganization(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise enableSharingWithAwsOrganizationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPermission(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPermissionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourcePolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourcePoliciesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourceShareAssociations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourceShareAssociationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourceShareInvitations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourceShareInvitationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getResourceShares(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getResourceSharesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPendingInvitationResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPendingInvitationResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPermissionVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPermissionVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPermissions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPermissionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPrincipals(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPrincipalsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listResourceSharePermissions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listResourceSharePermissionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listResourceTypes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listResourceTypesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result promoteResourceShareCreatedFromPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise promoteResourceShareCreatedFromPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result rejectResourceShareInvitation(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise rejectResourceShareInvitationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateResourceShare(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateResourceShareAsync(array $args = [])
 */
class RAMClient extends AwsClient {}
