<?php

namespace MediaCloud\Vendor\Aws\IoTTwinMaker;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS IoT TwinMaker** service.
 * @method \MediaCloud\Vendor\Aws\Result batchPutPropertyValues(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchPutPropertyValuesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createComponentType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createComponentTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createEntity(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createEntityAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createScene(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSceneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createWorkspace(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createWorkspaceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteComponentType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteComponentTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteEntity(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteEntityAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteScene(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSceneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteWorkspace(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteWorkspaceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getComponentType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getComponentTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getEntity(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getEntityAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPropertyValue(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPropertyValueAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPropertyValueHistory(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPropertyValueHistoryAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getScene(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSceneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getWorkspace(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getWorkspaceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listComponentTypes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listComponentTypesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listEntities(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listEntitiesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listScenes(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listScenesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listWorkspaces(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listWorkspacesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateComponentType(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateComponentTypeAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateEntity(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateEntityAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateScene(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSceneAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateWorkspace(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateWorkspaceAsync(array $args = [])
 */
class IoTTwinMakerClient extends AwsClient {}
