<?php

namespace MediaCloud\Vendor\Aws\ChimeSDKIdentity;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Chime SDK Identity** service.
 * @method \MediaCloud\Vendor\Aws\Result createAppInstance(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAppInstanceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createAppInstanceAdmin(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAppInstanceAdminAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createAppInstanceUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAppInstanceUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAppInstance(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppInstanceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAppInstanceAdmin(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppInstanceAdminAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAppInstanceUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppInstanceUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deregisterAppInstanceUserEndpoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deregisterAppInstanceUserEndpointAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppInstance(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppInstanceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppInstanceAdmin(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppInstanceAdminAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppInstanceUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppInstanceUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppInstanceUserEndpoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppInstanceUserEndpointAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAppInstanceRetentionSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAppInstanceRetentionSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppInstanceAdmins(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppInstanceAdminsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppInstanceUserEndpoints(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppInstanceUserEndpointsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppInstanceUsers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppInstanceUsersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppInstances(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppInstancesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putAppInstanceRetentionSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putAppInstanceRetentionSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result registerAppInstanceUserEndpoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise registerAppInstanceUserEndpointAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateAppInstance(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAppInstanceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateAppInstanceUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAppInstanceUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateAppInstanceUserEndpoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAppInstanceUserEndpointAsync(array $args = [])
 */
class ChimeSDKIdentityClient extends AwsClient {}
