<?php

namespace MediaCloud\Vendor\Aws\Shield;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Shield** service.
 * @method \MediaCloud\Vendor\Aws\Result associateDRTLogBucket(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateDRTLogBucketAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateDRTRole(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateDRTRoleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateHealthCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateHealthCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result associateProactiveEngagementDetails(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateProactiveEngagementDetailsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createProtection(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createProtectionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSubscription(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSubscriptionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProtection(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProtectionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSubscription(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSubscriptionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAttack(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAttackAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDRTAccess(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDRTAccessAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeEmergencyContactSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeEmergencyContactSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeProtection(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeProtectionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSubscription(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSubscriptionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disableProactiveEngagement(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disableProactiveEngagementAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateDRTLogBucket(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateDRTLogBucketAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateDRTRole(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateDRTRoleAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateHealthCheck(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateHealthCheckAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result enableProactiveEngagement(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise enableProactiveEngagementAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getSubscriptionState(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSubscriptionStateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAttacks(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAttacksAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProtections(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProtectionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateEmergencyContactSettings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateEmergencyContactSettingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSubscription(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSubscriptionAsync(array $args = [])
 */
class ShieldClient extends AwsClient {}
