<?php

namespace MediaCloud\Vendor\Aws\ResilienceHub;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Resilience Hub** service.
 * @method \MediaCloud\Vendor\Aws\Result addDraftAppVersionResourceMappings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise addDraftAppVersionResourceMappingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createApp(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAppAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createRecommendationTemplate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createRecommendationTemplateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createResiliencyPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createResiliencyPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteApp(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAppAssessment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppAssessmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteRecommendationTemplate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteRecommendationTemplateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteResiliencyPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteResiliencyPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeApp(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppAssessment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppAssessmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppVersionResourcesResolutionStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppVersionResourcesResolutionStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAppVersionTemplate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAppVersionTemplateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeDraftAppVersionResourcesImportStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeDraftAppVersionResourcesImportStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeResiliencyPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeResiliencyPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result importResourcesToDraftAppVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise importResourcesToDraftAppVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAlarmRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAlarmRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppAssessments(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppAssessmentsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppComponentCompliances(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppComponentCompliancesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppComponentRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppComponentRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppVersionResourceMappings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppVersionResourceMappingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppVersionResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppVersionResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listApps(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listRecommendationTemplates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listRecommendationTemplatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listResiliencyPolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listResiliencyPoliciesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSopRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSopRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSuggestedResiliencyPolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSuggestedResiliencyPoliciesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTestRecommendations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTestRecommendationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listUnsupportedAppVersionResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listUnsupportedAppVersionResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result publishAppVersion(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise publishAppVersionAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putDraftAppVersionTemplate(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putDraftAppVersionTemplateAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result removeDraftAppVersionResourceMappings(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise removeDraftAppVersionResourceMappingsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result resolveAppVersionResources(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise resolveAppVersionResourcesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result startAppAssessment(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise startAppAssessmentAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateApp(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateAppAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateResiliencyPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateResiliencyPolicyAsync(array $args = [])
 */
class ResilienceHubClient extends AwsClient {}
