<?php

namespace MediaCloud\Vendor\Aws\MemoryDB;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon MemoryDB** service.
 * @method \MediaCloud\Vendor\Aws\Result batchUpdateCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise batchUpdateClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result copySnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise copySnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createACL(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createACLAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createParameterGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createParameterGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createSubnetGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createSubnetGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteACL(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteACLAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteParameterGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteParameterGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSnapshot(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteSubnetGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteSubnetGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteUserAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeACLs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeACLsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeClusters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeClustersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeEngineVersions(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeEngineVersionsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeEvents(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeParameterGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeParameterGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeParameters(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeParametersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeServiceUpdates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeServiceUpdatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSnapshots(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeSubnetGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeSubnetGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeUsers(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeUsersAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result failoverShard(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise failoverShardAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAllowedNodeTypeUpdates(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAllowedNodeTypeUpdatesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTags(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result resetParameterGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise resetParameterGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateACL(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateACLAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateCluster(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateClusterAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateParameterGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateParameterGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateSubnetGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateSubnetGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateUser(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateUserAsync(array $args = [])
 */
class MemoryDBClient extends AwsClient {}
