<?php

namespace MediaCloud\Vendor\Aws\GroundStation;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **AWS Ground Station** service.
 * @method \MediaCloud\Vendor\Aws\Result cancelContact(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise cancelContactAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createDataflowEndpointGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createDataflowEndpointGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createMissionProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createMissionProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteDataflowEndpointGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteDataflowEndpointGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteMissionProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteMissionProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeContact(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeContactAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMissionProfileConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMissionProfileConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getDataflowEndpointGroup(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getDataflowEndpointGroupAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMinuteUsage(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMinuteUsageAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getMissionProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getMissionProfileAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getSatellite(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getSatelliteAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listConfigs(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listConfigsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listContacts(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listContactsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listDataflowEndpointGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listDataflowEndpointGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listGroundStations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listGroundStationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listMissionProfiles(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listMissionProfilesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listSatellites(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listSatellitesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result reserveContact(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise reserveContactAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateConfig(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateConfigAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateMissionProfile(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateMissionProfileAsync(array $args = [])
 */
class GroundStationClient extends AwsClient {}
