<?php

namespace MediaCloud\Vendor\Aws\FMS;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with the **Firewall Management Service** service.
 * @method \MediaCloud\Vendor\Aws\Result associateAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise associateAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAppsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAppsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteNotificationChannel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteNotificationChannelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deletePolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deletePolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteProtocolsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteProtocolsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result disassociateAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise disassociateAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAdminAccount(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAdminAccountAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getAppsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getAppsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getComplianceDetail(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getComplianceDetailAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getNotificationChannel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getNotificationChannelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getProtectionStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getProtectionStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getProtocolsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getProtocolsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result getViolationDetails(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise getViolationDetailsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listAppsLists(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listAppsListsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listComplianceStatus(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listComplianceStatusAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listMemberAccounts(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listMemberAccountsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listPolicies(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listPoliciesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listProtocolsLists(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listProtocolsListsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putAppsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putAppsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putNotificationChannel(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putNotificationChannelAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putProtocolsList(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putProtocolsListAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 */
class FMSClient extends AwsClient {}
