<?php

namespace MediaCloud\Vendor\Aws\Efs;
use MediaCloud\Vendor\Aws\AwsClient;

/**
 * This client is used to interact with **Amazon EFS**.
 *
 * @method \MediaCloud\Vendor\Aws\Result createAccessPoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createAccessPointAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createFileSystemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createMountTarget(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createMountTargetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createReplicationConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createReplicationConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result createTags(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise createTagsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteAccessPoint(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteAccessPointAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteFileSystemAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteFileSystemPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteFileSystemPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteMountTarget(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteMountTargetAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteReplicationConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteReplicationConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result deleteTags(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise deleteTagsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAccessPoints(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAccessPointsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeAccountPreferences(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeAccountPreferencesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeBackupPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeBackupPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeFileSystemPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeFileSystemPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeFileSystems(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeFileSystemsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeLifecycleConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeLifecycleConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeMountTargetSecurityGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeMountTargetSecurityGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeMountTargets(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeMountTargetsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeReplicationConfigurations(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeReplicationConfigurationsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result describeTags(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result listTagsForResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result modifyMountTargetSecurityGroups(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise modifyMountTargetSecurityGroupsAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putAccountPreferences(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putAccountPreferencesAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putBackupPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putBackupPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putFileSystemPolicy(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putFileSystemPolicyAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result putLifecycleConfiguration(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise putLifecycleConfigurationAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result tagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result untagResource(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \MediaCloud\Vendor\Aws\Result updateFileSystem(array $args = [])
 * @method \MediaCloud\Vendor\GuzzleHttp\Promise\Promise updateFileSystemAsync(array $args = [])
 */
class EfsClient extends AwsClient {}
