<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/checked.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Decl\FunctionDecl instead.
     * @deprecated
     */
    class Decl_FunctionDecl {}
}
class_exists(Decl\FunctionDecl::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Decl_FunctionDecl is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Decl\FunctionDecl instead', E_USER_DEPRECATED);

