<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/syntax.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr\Call instead.
     * @deprecated
     */
    class Expr_Call {}
}
class_exists(Expr\Call::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr_Call is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr\Call instead', E_USER_DEPRECATED);

