<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/syntax.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr\CreateStruct\Entry instead.
     * @deprecated
     */
    class Expr_CreateStruct_Entry {}
}
class_exists(Expr\CreateStruct\Entry::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr_CreateStruct_Entry is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Expr\CreateStruct\Entry instead', E_USER_DEPRECATED);

