<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/value.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBType;
use MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField;
use MediaCloud\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * A list.
 * Wrapped in a message so 'not set' and empty can be differentiated, which is
 * required for use in a 'oneof'.
 *
 * Generated from protobuf message <code>google.api.expr.v1alpha1.ListValue</code>
 */
class ListValue extends \MediaCloud\Vendor\Google\Protobuf\Internal\Message
{
    /**
     * The ordered values in the list.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Value values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Value[]|\Google\Protobuf\Internal\RepeatedField $values
     *           The ordered values in the list.
     * }
     */
    public function __construct($data = NULL) { \MediaCloud\Vendor\GPBMetadata\Google\Api\Expr\V1Alpha1\Value::initOnce();
        parent::__construct($data);
    }

    /**
     * The ordered values in the list.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Value values = 1;</code>
     * @return \MediaCloud\Vendor\Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * The ordered values in the list.
     *
     * Generated from protobuf field <code>repeated .google.api.expr.v1alpha1.Value values = 1;</code>
     * @param \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Value[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \MediaCloud\Vendor\Google\Protobuf\Internal\GPBType::MESSAGE, \MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Value::class);
        $this->values = $arr;

        return $this;
    }

}

