<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/checked.proto

namespace MediaCloud\Vendor\Google\Api\Expr\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type\MapType instead.
     * @deprecated
     */
    class Type_MapType {}
}
class_exists(Type\MapType::class);
@trigger_error('MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type_MapType is deprecated and will be removed in the next major release. Use MediaCloud\Vendor\Google\Api\Expr\V1alpha1\Type\MapType instead', E_USER_DEPRECATED);

